.gitignore

Better Add GitIgnore list here

Update Git Ignore list

---

TFT/src/User/API/interfaceCmd.c
TFT/src/User/Menu/menu.c

Prepare Parse Gcode Function

---

TFT/src/User/API/boot.c

Boot.C White Space CleanUp

---

TFT/src/User/API/Vfs/vfs.c
TFT/src/User/Menu/Heat.c

Surpress Variable Init Warning

Fix Variable init warning

---

TFT/src/User/API/interfaceCmd.c
TFT/src/User/API/interfaceCmd.h
TFT/src/User/API/parseACK.c
TFT/src/User/API/parseACK.h
TFT/src/User/Hal/stm32f10x/Serial.c
TFT/src/User/Hal/stm32f10x/Serial.h
TFT/src/User/Hal/stm32f10x/usart.h
TFT/src/User/Hal/stm32f2xx/Serial.c
TFT/src/User/Hal/stm32f2xx/Serial.h
TFT/src/User/Menu/PowerFailed.c
TFT/src/User/Menu/Print.c
TFT/src/User/Menu/Printing.c
TFT/src/User/Menu/menu.c
TFT/src/User/includes.h
TFT/src/User/variants.h
platformio.ini

add multi-serial port for ESP3D or other UART controller

add multi-serial port

---

TFT/src/User/Configuration.h
TFT/src/User/Menu/Mode.c

i hope i dont offend you guys, but i added an option to hide the 3 seconds bootscreen.

added option to hide bootscreen

---

TFT/src/User/API/extend.c
TFT/src/User/Menu/ScreenSettings.c

fix for TFT35 V3, TFT24 V1.1 still unresolved

fix for TFT35 V3

---

.github/workflows/buildTest.yml

auto build test using GitHub actions after each pull request to prevent compile errors

automatic build test using GitHub actions

---

.github/workflows/buildTest.yml

Not all changes make their way in via PR, so this will start a build test for direct pushes as well.

Add Push to GitHub Actions

---

TFT/src/User/API/Language/Language.h
TFT/src/User/API/UI/list_item.c
TFT/src/User/API/UI/list_item.h
TFT/src/User/API/boot.h
TFT/src/User/Menu/Print.c
TFT/src/User/Menu/Printing.c
TFT/src/User/Menu/Speed.c
TFT/src/User/Menu/StatusScreen.c
TFT/src/User/Menu/menu.c
TFT/src/User/Menu/menu.h

- clean up menu API, fix `uint16_t ` to `uint8_t *` bugs 
- NEED more clean up for menu API

clean up menu API

---

TFT/src/User/API/boot.c

Fix setting not saved on forced reset through reset.txt file.

Fix setting not saved on forced reset through reset.txt file.

---

TFT/src/User/Menu/BabyStep.c
TFT/src/User/Menu/Print.c
TFT/src/User/Menu/ProbeOffset.c

This reverts commit ed712a7f75bd3db213789538c42e2a1ca98ca2b8.

Revert "fix negative value display Z-offset and BabyStep (float number)"

---

TFT/src/User/Menu/BabyStep.c
TFT/src/User/Menu/Print.c

improve disable onBoardSD display

---

TFT/src/User/API/parseACK.c
TFT/src/User/Configuration.h
TFT/src/User/Menu/Printing.c
TFT/src/User/Menu/leveling.c
TFT/src/User/my_misc.c

fix -0.12f be converted to 0.12 bug in my_sprintf bug,  add auto save & load leveling value config, 

---

TFT/src/User/Configuration.h
TFT/src/User/Menu/PowerFailed.c
TFT/src/User/Menu/Printing.c

fix resume filament purge length bug

---

TFT/src/User/Menu/PowerFailed.c

fix resume print after power failed z raise

---

TFT/src/User/API/boot.h
TFT/src/User/Menu/Parametersetting.c
TFT/src/User/Menu/Parametersetting.h
TFT/src/User/Menu/Print.c
TFT/src/User/Menu/Print.h
TFT/src/User/Menu/Printing.c
TFT/src/User/Menu/menu.c

Reduce the number of flash writes and naming conventions

Reduce the number of flash writes and naming conventions

---

TFT/src/User/Hal/stm32f10x/lcd.h
TFT/src/User/Hal/stm32f2xx/lcd.h

Clean up WhiteSpace and Delete unused Color Definition (BRED and GRED)

Clean Up Color Definition

---

TFT/src/User/API/UI/list_item.h
TFT/src/User/API/flashStore.c
TFT/src/User/Configuration.h
TFT/src/User/Menu/FeatureSettings.c
TFT/src/User/Menu/Move.c
TFT/src/User/Menu/Parametersetting.c
TFT/src/User/Menu/Settings.c
TFT/src/User/Menu/Settings.h
TFT/src/User/Menu/ledcolor.c
TFT/src/User/Menu/ledcolor.h
TFT/src/User/main.c

clean up move.c & default config disable AUTO_SAVE_LOAD_LEVELING_VALUE

---

TFT/src/User/Menu/MainPage.c
TFT/src/User/Menu/Mode.c

delete status screen in classic ui,  keep it simple

---

.editorconfig
TFT/src/User/Hal/stm32f10x/lcd.h
TFT/src/User/Hal/xpt2046.c
TFT/src/User/Menu/ledcolor.h
TFT/src/User/my_misc.c
TFT/src/User/my_misc.h

Add editorconfig file to ensure proper encoding, line endings, remove trailing whitespace, etc. on save.
And where possible, revert Chinese character encoding errors & translate comments to English.
See above.
None.

Add editorconfig file, fix encoding, translate comments to English

---

TFT/src/User/API/interfaceCmd.c
TFT/src/User/API/parseACK.c
TFT/src/User/Menu/Heat.c
TFT/src/User/Menu/Heat.h

fix M104/M140/M109/M190 'B' 'F', etc... parameters bug

---

TFT/src/User/API/UI/touch_process.c
TFT/src/User/API/UI/touch_process.h
TFT/src/User/API/interfaceCmd.c
TFT/src/User/Configuration.h
TFT/src/User/Hal/buzzer.c
TFT/src/User/Hal/buzzer.h
TFT/src/User/Hal/stm32f10x/GPIO_Init.c
TFT/src/User/Hal/stm32f10x/GPIO_Init.h
TFT/src/User/Hal/stm32f2xx/GPIO_Init.c
TFT/src/User/Hal/stm32f2xx/GPIO_Init.h
TFT/src/User/Menu/menu.c
TFT/src/User/includes.h

support M300 for TFT Buzzer.
for #404

add M300 support for buzzer

---

README.md

Thanks to  @Hukuma1, the UI previews have been greatly improved. [Preview](https://github.com/thisiskeithb/BIGTREETECH-TouchScreenFirmware/tree/pr/improve_readme_config_cleanup#menus-and-themes)
Prettier preview images.
#418

Improve UI previews in readme

---

TFT/src/User/Hal/buzzer.c

Fix for silent mode

---

TFT/src/User/Hal/stm32f10x/usart.h
TFT/src/User/Menu/Mode.c
TFT/src/User/Menu/Parametersetting.c

fixed some compile warnings

---

TFT/src/User/Menu/Printing.c

"Stop" button change to "Back" button, will always stay in "Back" when printing again
follow up #467

fix printing "back" button

---

platformio.ini

Change startup for mks boards in platformio.ini , fix for working usb

Change startup for mks boards, fix for working usb

---

TFT/src/User/Menu/Print.c

fixed #533 
This is just a temporary solution. it can print normally from u disk in my testing. More debugging is needed to find the root reason

comment out preview model function for print from U disk

---

TFT/src/User/Menu/Move.c

fix move.c M114 cycle

---

TFT/src/User/API/parseACK.c
TFT/src/User/Menu/StatusScreen.c

fix multi-serial(ESP3D, etc...) bug after #168

---

TFT/src/User/API/UI/Numpad.c

fix if(x = xx) bug

---

TFT/src/User/API/UI/ST7920_Simulator.c

fix st7920 bugs after #705 
#709

fix st7920 bug after (#705)

---

TFT/src/User/API/parseACK.c
TFT/src/User/Menu/Move.c

fix UART data parse logic to avoid possible hang

---

TFT/src/User/API/extend.c
TFT/src/User/API/extend.h
TFT/src/User/API/parseACK.c
TFT/src/User/Menu/Printing.c
TFT/src/User/Menu/Printing.h
TFT/src/User/Menu/menu.c

fix runout dialog be overwritten bt printing menu

---

Copy to SD Card root directory to update - Unified Menu Material theme/config.ini
Copy to SD Card root directory to update/config.ini
TFT/src/User/API/Colors.c
TFT/src/User/API/Colors.h
TFT/src/User/API/UI/GUI.c
TFT/src/User/API/UI/ST7920_Simulator.c
TFT/src/User/API/UI/list_item.c
TFT/src/User/API/boot.c
TFT/src/User/API/config.c
TFT/src/User/Menu/Mode.c
TFT/src/User/Menu/Move.c
TFT/src/User/Menu/PowerFailed.c
TFT/src/User/Menu/Print.c
TFT/src/User/Menu/ScreenSettings.c
TFT/src/User/Menu/Settings.c
TFT/src/User/Menu/Settings.h
TFT/src/User/Menu/StatusScreen.c
TFT/src/User/Menu/menu.c

improve the config color option, set hex color value(RGB888 format) directly
#699 
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/526#issuecomment-610201284

improve the config color option, set hex color value(RGB888 format) directly

---

Copy to SD Card root directory to update - Unified Menu Material theme/config.ini
Copy to SD Card root directory to update/config.ini
TFT/src/User/API/UI/GUI.c
TFT/src/User/API/UI/GUI.h
TFT/src/User/API/parseACK.c
TFT/src/User/config.ini

- Add parsing of Fan speed
- Fix: 'T0' temperature updating to current tool/nozzle
- Fix: typo (raido > radio)
- Fix: wrong gcode in config.ini
Fixes #779

Fix wrong Gcode in Config.ini, 'T0' temperature updating to current tool/nozzle, Add parsing of Fan speed

---

config_instructions.md

Fixed typos in config_instructions.md
With this fix, the typos in step 7 no longer appear.
None.

Spelling fixes

---

TFT/src/User/API/FanControl.c

Correction of cycling of the fan speed value when changing speed.
Described in #826
resolves #836

Fan speed repair

---

TFT/src/User/API/FanControl.c
TFT/src/User/API/SpeedControl.c
TFT/src/User/API/interfaceCmd.c

Fix the problem
If code M220 or M221 is used for printing, the value on the display will not be updated

Speed value update

---

TFT/src/User/API/ledcolor.c
TFT/src/User/Menu/SettingsMenu.c

Baudrate change to list select from toggle

fix Baudrate select menu

---

TFT/src/User/API/UI/ui_draw.c
TFT/src/User/Menu/SettingsMenu.c
TFT/src/User/my_misc.c

Fixed compile warnings

---

TFT/src/User/API/interfaceCmd.c

fix Error parse M109 Tx Sxxx bug

---

TFT/src/User/Menu/leveling.c

Fix machine size min for second point.

Fix point 2 of leveling

---

TFT/src/User/Menu/PowerFailed.c

fix PLR dialog type to QUESTION from ERROR

---

Copy to SD Card root directory to update - Unified Menu Material theme/config.ini
Copy to SD Card root directory to update/config.ini
TFT/src/User/API/MachineParameters.c
TFT/src/User/API/Printing.c
TFT/src/User/API/interfaceCmd.c
TFT/src/User/API/interfaceCmd.h
TFT/src/User/Menu/MachineSettings.c

add store script funtion

---

TFT/src/User/API/interfaceCmd.c
TFT/src/User/Menu/Parametersetting.c
TFT/src/User/Menu/Parametersetting.h
TFT/src/User/Menu/levelingUBLLoad.c
TFT/src/User/Menu/levelingUBLSave.c
TFT/src/User/Menu/menu.c

* improve temperature status display reduce redraw flicker
* fix mustStoreScript bug #895 #898

fix mustStoreScript bug,  improve temperature status display reduce redraw flicker

---

TFT/src/User/API/LCD_Encoder.c
TFT/src/User/API/LCD_Encoder.h
TFT/src/User/API/UI/HD44780_Simulator.c
TFT/src/User/API/UI/touch_process.c
TFT/src/User/API/ledcolor.c
TFT/src/User/Hal/LCD_Init.c
TFT/src/User/Hal/LCD_Init.h
TFT/src/User/Menu/ConnectionSettings.c
TFT/src/User/Menu/MarlinMode.c
TFT/src/User/Menu/Mode.c
TFT/src/User/Menu/Selectmode.c
TFT/src/User/Menu/SettingsMenu.c
TFT/src/User/Menu/menu.c

move dim process part from interrupt to loop, avoid the occupation of interrupts

improve dim，  move it from interrupt to loop

---

TFT/src/User/Hal/HD44780.c
TFT/src/User/Hal/stm32f10x/spi_slave.c
TFT/src/User/Hal/stm32f10x/spi_slave.h
TFT/src/User/Hal/stm32f10x/spi_slave_mks.c
TFT/src/User/Hal/stm32f2_f4xx/spi_slave.c

fix stm32f10x  spi_slave(lcd12864)

---

TFT/src/User/API/UI/GUI.c
TFT/src/User/API/UI/GUI.h
TFT/src/User/API/parseACK.c
TFT/src/User/Menu/ScreenSettings.c
TFT/src/User/Menu/SettingsMenu.c
TFT/src/User/Menu/SettingsMenu.h
TFT/src/User/Menu/StatusScreen.c
TFT/src/User/Menu/StatusScreen.h

* display Marlin version & machine type in info menu
* display “Machine Ready” instead of “Ready" in StatusScreen menu
#795

display Marlin version & machine type in info menu

---

TFT/src/User/API/parseACK.c

Compatible Repetier

---

TFT/src/User/API/FanControl.c
TFT/src/User/API/FanControl.h
TFT/src/User/API/interfaceCmd.c
TFT/src/User/Hal/HD44780.c
TFT/src/User/Hal/HD44780.h
TFT/src/User/Menu/Fan.c
TFT/src/User/Menu/Fan.h

* When fan_count = 2, F0 can be controlled normally but F1 will not work.

fix multi fan not work bug

---

TFT/src/User/API/interfaceCmd.c
TFT/src/User/Configuration.h
TFT/src/User/Menu/PrintingMenu.c
TFT/src/User/Menu/SettingsMenu.c

* default support M601 gcode pause, add M600 same as M601 
* restore font color when leave info menu, otherwise font color is Gray
#965 
#966

default support M601 gcode pause, add M600 same as M601

---

TFT/src/User/API/FanControl.c
TFT/src/User/Configuration.h
TFT/src/User/Menu/Fan.c
TFT/src/User/Menu/MachineSettings.c
TFT/src/User/Menu/MainPage.c
TFT/src/User/Menu/SettingsMenu.c

- Move the tuning menu to machine settings
- Simplify EEPROM buttons.
- Fix fan speed display issue (#883)
Fixes #883

move tuning menu to machine setting and simplify eeprom buttons, Fix fan speed display issue

---

TFT/src/User/API/FanControl.c
TFT/src/User/API/FanControl.h
TFT/src/User/Menu/Fan.c

fix fan double click add 1%

---

TFT/src/User/API/menu.c

Added array size check to make sure color index is within the array.
Prevents freezing on the status screen on TFT24 screens.
#999

Changed to prevent freezing seen on TFT24 screens.

---

TFT/src/User/API/Language/language_hu.h

I updated the Hungarian language file.
1 icon has been deleted from the Hybrid Red Menu ZIP folder on the displays. Just what you don't need.
Hello, AntoszHUN

Updated language_hu.h file

---

TFT/src/User/API/LCD_Encoder.c
TFT/src/User/API/UI/GUI.c
TFT/src/User/Hal/stm32f10x/sdio_sdcard.h

Fixed compiler warnings

---

TFT/src/User/Menu/Mode.c
TFT/src/User/main.c

Fixed an issue with loading printer parameters when switching from marlin mode to touch mode.
look #1297

Fixed MachineSetting

---

Copy to SD Card root directory to update/Language Packs/language_hu.ini
TFT/src/User/API/Language/language_hu.h

Update the latest language add-ons.
By: AntoszHUN

Update Hungarian language.

---

Copy to SD Card root directory to update/Language Packs/language_cz.ini
TFT/src/User/API/Language/language_cz.h

Update CZ language

---

Copy to SD Card root directory to update/Language Packs/language_it.ini
TFT/src/User/API/Language/language_it.h

Update italian language

---

Copy to SD Card root directory to update/Language Packs/language_ru.ini
TFT/src/User/API/Language/language_ru.h

Update Russian Translate

---

Copy to SD Card root directory to update/Language Packs/language_hu.ini
TFT/src/User/API/Language/language_hu.h

- I also made the fix in the language_hu.h and language_hu.ini files.
- The length of the word "Force" was incorrect. This has been fixed by removing a syllable.
Made By.: AntoszHUN

Minor fix in the language_hu.h file

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

The idea of this pull request is to solve the PlatformIO install issue on Windows 10 by using a docker container with Visual Studio Code.
* Requires Docker to be installed
* Only Tested on Windows 10 20H2 using WSL2 + Docker Desktop

Create Devcontainer for VSCode

---

Copy to SD Card root directory to update/Language Packs/language_de.ini
Copy to SD Card root directory to update/config.ini
TFT/src/User/API/Language/language_de.h
TFT/src/User/API/UI/Numpad.c
TFT/src/User/API/UI/list_item.h
TFT/src/User/API/UI/list_widget.c
TFT/src/User/API/config.c
TFT/src/User/API/interfaceCmd.c
TFT/src/User/Menu/ABL.c
TFT/src/User/Menu/BedLeveling.c
TFT/src/User/Menu/ConnectionSettings.c
TFT/src/User/Menu/Extrude.c
TFT/src/User/Menu/Fan.c
TFT/src/User/Menu/Fan.h
TFT/src/User/Menu/Leveling.c
TFT/src/User/Menu/LoadUnload.c
TFT/src/User/Menu/Move.c
TFT/src/User/Menu/NotificationMenu.c
TFT/src/User/Menu/Parametersetting.c
TFT/src/User/Menu/PrintingMenu.h
TFT/src/User/Menu/SendGcode.c
TFT/src/User/Menu/Speed.h
TFT/src/User/config.ini

Just a cleanup on last config.ini
fixes #1467
fixes #1474

config.ini cleanup

---

TFT/src/User/API/Language/language_it.h

Enhanced italian language

---

TFT/src/User/API/Gcode/gcode.c
TFT/src/User/API/Gcode/gcode.h
TFT/src/User/API/Vfs/vfs.c
TFT/src/User/Menu/PrintingMenu.c

Implemet Print from SD-Card for RepRapFirmware
* No Requirements known 
* 
RepRapFirmware is different with commands M23 and M21. M21 is not allows wen printing and creates an error. M23 not responce the size of the file. To get the size of the file RepRapFirmware use M36
Start printing SD-Card files from Display
#1400

Implemet Print from SD-Crd for RepRapFirmware

---

Copy to SD Card root directory to update/Language Packs/language_hu.ini
TFT/src/User/API/Language/language_hu.h

I updated the Hungarian language files.
Translation of the newly added elements into Hungarian.
These were done in the language_hu.h and language_hu.ini files.
Grammar errors may still occur.
Their improvement is continuous.
Made By: AntoszHUN

Updated Hungarian Language

---

Copy to SD Card root directory to update/Language Packs/language_es.ini
TFT/src/User/API/Language/language_es.h
TFT/src/User/API/Vfs/vfs.c

will be label_pl_recovery_en
label_pl_recovery_en is the correct label, or send a error when install.

label_pl_recovery_en bad label

---

TFT/src/User/Menu/TuneExtruder.c

fix TFT43/50/70 Adjust E-Steps menu bug

fix TFT43/50/70 Adjust E-Steps menu bug

---

Copy to SD Card root directory to update/Language Packs/language_hu.ini
TFT/src/User/API/Language/language_hu.h
TFT/src/User/Configuration.h

I fixed a couple of eye-popping bugs.
- Minor fixes to language_hu.h and language_hu.ini.
- Fixed extruder display in configuration.h file.
- Everywhere E0, E1, E2 and so on continue. Therefore, (E) was corrected for (E0) and (E2) was corrected for (E1).
Made By: AntoszHUN

Minor fixes

---

TFT/src/User/API/interfaceCmd.c
TFT/src/User/API/parseACK.c

Sorting of parameters according to the M-code number on the PR created by me

Sorting of parameters according to the M-code number

---

TFT/src/User/API/MachineParameters.c
TFT/src/User/API/boot.c
TFT/src/User/API/config.h

bugs test and fix for stable version 

---

buildroot/ldscripts/stm32f105xC_0x6000_iap.ld

fix TFT24 start flash address
fix #1684

fix TFT24 start flash address

---

TFT/src/User/API/FanControl.c
TFT/src/User/API/FanControl.h
TFT/src/User/API/UI/GUI.c
TFT/src/User/API/UI/GUI.h
TFT/src/User/API/config.c
TFT/src/User/API/interfaceCmd.c
TFT/src/User/API/parseACK.c
TFT/src/User/Menu/Fan.c
TFT/src/User/Menu/Fan.h
TFT/src/User/Menu/PrintingMenu.c
TFT/src/User/Menu/SendGcode.c
TFT/src/User/Menu/common.c

cleanup & fix controller_fan

---

TFT/src/User/API/FanControl.c
TFT/src/User/API/FanControl.h
TFT/src/User/API/UI/GUI.c
TFT/src/User/API/UI/GUI.h
TFT/src/User/API/config.c
TFT/src/User/API/interfaceCmd.c
TFT/src/User/API/parseACK.c
TFT/src/User/Menu/Fan.c
TFT/src/User/Menu/Fan.h
TFT/src/User/Menu/PrintingMenu.c
TFT/src/User/Menu/SendGcode.c
TFT/src/User/Menu/common.c

Reverts bigtreetech/BIGTREETECH-TouchScreenFirmware#1712

Revert "cleanup & fix controller_fan"

---

TFT/src/User/API/interfaceCmd.c

fix controller fan

---

TFT/src/User/API/SpeedControl.c
TFT/src/User/API/interfaceCmd.c
TFT/src/User/API/parseACK.c
TFT/src/User/Menu/BedLeveling.c
TFT/src/User/Menu/Extrude.c
TFT/src/User/Menu/Speed.c

* fix extrude mm update not in realtime bug
* fix M221 D para to HIGH bug (`T0 P0` need in sys `config.g` avoid `No tool selected` error)
* fix RRF ABL staus M420 bad command

fix extrude mm update not in realtime bug & RRF support improve

---

TFT/src/User/API/Printing.c

printing menu cannot preview model bug

---

Copy to SD Card root directory to update/config.ini
Copy to SD Card root directory to update/config_rrf.ini
TFT/src/User/API/Printing.c
TFT/src/User/API/Printing.h
TFT/src/User/API/Settings.c
TFT/src/User/API/Settings.h
TFT/src/User/API/Vfs/vfs.c
TFT/src/User/API/Vfs/vfs.h
TFT/src/User/API/config.c
TFT/src/User/Menu/Leveling.c
TFT/src/User/Menu/PrintingMenu.c
TFT/src/User/config.ini

* Delete useless judgments in `reDrawProgress` for clean
* Separate y-axis invert for manual leveling menu
* clean up `infoPrinting` struct

 separate y-axis invert for manual leveling menu

---

TFT/src/User/API/Language/Language.c
TFT/src/User/API/Language/language_am.h
TFT/src/User/API/Language/language_ca.h
TFT/src/User/API/Language/language_cn.h
TFT/src/User/API/Language/language_cz.h
TFT/src/User/API/Language/language_de.h
TFT/src/User/API/Language/language_du.h
TFT/src/User/API/Language/language_en.h
TFT/src/User/API/Language/language_es.h
TFT/src/User/API/Language/language_fr.h
TFT/src/User/API/Language/language_gr.h
TFT/src/User/API/Language/language_hu.h
TFT/src/User/API/Language/language_it.h
TFT/src/User/API/Language/language_jp.h
TFT/src/User/API/Language/language_keywords.h
TFT/src/User/API/Language/language_pl.h
TFT/src/User/API/coordinate.c
TFT/src/User/API/coordinate.h
TFT/src/User/API/menu.h
TFT/src/User/API/parseACK.c
TFT/src/User/Menu/BedLevelingLayer2.c
TFT/src/User/Menu/LevelCorner.c

cleanup on last merged PR

---

TFT/src/User/API/UI/Numpad.c

misc cleanup and reset value fix in numpad.c

misc cleanup and reset value fix in numpad.c

---

Copy to SD Card root directory to update/Language Packs/language_it.ini
TFT/src/User/API/Language/language_it.h

Enhanced italian translation

---

TFT/src/User/API/Gcode/gcode.c
TFT/src/User/Menu/MainPage.c
TFT/src/User/Menu/RRFMacros.c

fix & improve RRF Macros

---

platformio.ini

*  Restructure platformio.ini File, using the relying on expansion to avoid redundancy
#1830

cleanup platformio.ini

---

TFT/src/User/API/Gcode/gcode.c
TFT/src/User/API/Gcode/gcode.h
TFT/src/User/API/UI/GUI.c
TFT/src/User/API/UI/GUI.h
TFT/src/User/Menu/MainPage.c
TFT/src/User/Menu/RRFMacros.c
TFT/src/User/Menu/Terminal.c

* I'm not sure about the role and necessity of `void send_and_wait_M20(const char* command)`. The current code works perfectly in my tests. Please tell me more if anyone knows about `void send_and_wait_M20(const char* command)`
Maybe  @pfn knows？
* Clean up `GUI_DispOne`.
* Clean up RRF macros & fix some `malloc` have not `free` bug.

Cleanup GUI & RRF macros menu

---

TFT/src/User/Menu/ConnectionSettings.c
TFT/src/User/Menu/ScreenSettings.c

fix baudrate menu freeze bug

---

TFT/src/User/API/Printing.c
TFT/src/User/API/Temperature.c
TFT/src/User/API/Temperature.h
TFT/src/User/API/parseACK.c
TFT/src/User/Menu/Heat.c
TFT/src/User/Menu/Pid.c
TFT/src/User/Menu/PowerFailed.c

* fix PLR Busy processing bug
* ~fix PLR active all heater include invaild T~

Fix PLR bug

---

TFT/src/User/API/Printing.c
TFT/src/User/API/Printing.h
TFT/src/User/API/Vfs/vfs.h
TFT/src/User/API/interfaceCmd.c
TFT/src/User/API/parseACK.c
TFT/src/User/Configuration.h
TFT/src/User/Menu/PrintingMenu.c
TFT/src/User/Menu/SettingsMenu.c
TFT/src/User/Variants/pin_MKS_TFT32_V1_4.h
TFT/src/User/Variants/pin_TFT35_V2_0.h
TFT/src/User/Variants/pin_TFT35_V3_0.h

Only a minor misc cleanup
**PR STATE:** ready for merging

minor cleanup

---

TFT/src/User/API/Language/language_keywords.h

Fix typo after PR #1908

---

TFT/src/User/API/CaseLightControl.c
TFT/src/User/API/CaseLightControl.h
TFT/src/User/API/Settings.c
TFT/src/User/API/Settings.h
TFT/src/User/API/Temperature.c
TFT/src/User/API/Temperature.h
TFT/src/User/API/UI/ui_draw.c
TFT/src/User/API/UI/ui_draw.h
TFT/src/User/API/boot.c
TFT/src/User/API/config.c
TFT/src/User/API/coordinate.c
TFT/src/User/Menu/CaseLight.c
TFT/src/User/Menu/MeshValid.c
TFT/src/User/Menu/PrintingMenu.c
TFT/src/User/Menu/StatusScreen.c
TFT/src/User/Menu/common.c

- Fix Power supply invert logic not working. (#1893)
- Remove unused setting variable.
- Remove the Babystepping icon from mesh validation menu.
- Misc code clean-up to reduce program memory.
Fixes: #1893

Fix power supply bug

---

TFT/src/User/API/Settings.h

- Update settings check signature format to ensure outdated settings are checked against both address and size changes.

update settings signature format

---

TFT/src/User/API/UI/GUI.c
TFT/src/User/API/UI/GUI.h
TFT/src/User/API/UI/ui_draw.c
TFT/src/User/API/UI/ui_draw.h
TFT/src/User/API/menu.c
TFT/src/User/Configuration.h
TFT/src/User/Menu/PrintingMenu.c
TFT/src/User/Menu/StatusScreen.c

After calling `ICON_PrepareRead`, set the background color of the text to the corresponding icon.

read background color from icon for text

---

Copy to SD Card root directory to update/Language Packs/language_it.ini
TFT/src/User/API/Language/language_it.h

Italian language update, I'm sorry if I hadn't correct also the INI file but I've got some problems with VSC

Italian language update

---

TFT/src/User/API/menu.c
TFT/src/User/API/menu.h
TFT/src/User/Menu/common.c

- Remove duplicate code to display values to reduce program memory usage.
- Misc cleanup.

Remove duplicate code and reduce program memory

---

TFT/src/User/API/Printing.c
TFT/src/User/API/extend.c

- Fix runout trigger during resuming which is causing runout to trigger during resuming. (#2024)
Fixes #2024

Fix runout trigger during resume

---

Copy to SD Card root directory to update/Language Packs/language_cz.ini
TFT/src/User/API/Language/language_cz.h

Translation CZ

---

Copy to SD Card root directory to update/Language Packs/language_hu.ini
TFT/src/User/API/Language/language_hu.h

Translate newly added words.
Update: in language_hu.ini and language_hu.h files.
Made by: AntoszHUN

Hungarian language update

---

TFT/src/User/API/Settings.h
TFT/src/User/Menu/Popup.c
TFT/src/User/Menu/RRFMacrosParser.cpp

**BUGFIX:**
*Fix for a bug introduced by my last merged PR #2082 preventing to display the dialog box asking to start the print for the selected file.
**BUG SEVERITY:** Major
**PR STATE:** ready to merge

fixed bug preventing to select and print a file

---

TFT/src/User/API/FlashStore.c
TFT/src/User/API/menu.c
TFT/src/User/Menu/PrintingMenu.c

* TFT70 print doen menu display bug(MainMenu button not work)

fix TFT70 print doen menu display bug

---

Copy to SD Card root directory to update/Language Packs/language_cz.ini
TFT/src/User/API/Language/language_cz.h

Translation to Czech

---

Copy to SD Card root directory to update/Language Packs/language_hu.ini
TFT/src/User/API/Language/language_hu.h

I updated the Hungarian language.
- Update in the translation of the new words into Hungarian.
- Fixes made to both files.
- Files: language_hu.h and language_hu.ini
I am constantly improving the language pack.
Made by: AntoszHUN

Update Hungarian language

---

TFT/src/User/API/interfaceCmd.c
TFT/src/User/Hal/stm32f2_f4xx/lcd_dma.c

fix E1 Steps per mm setting bugs

---

TFT/src/User/API/LCD_Colors.h
TFT/src/User/API/Settings.h
TFT/src/User/Configuration.h
TFT/src/User/Menu/PrintingMenu.c
TFT/src/User/SanityCheck.h

Color choices added for progress bar during print.
The choices are: 
- Orange
- Yellow
- Red
- Green
- Blue
- Cyan
- Magenta
- Purple
- Lime
- Gray
The color of the progress bar can be set at compile time in the "Configuration.h" by setting `PROGRESS_BAR_COLOR`.
#2272

Progress bar color

---

TFT/src/User/API/Vfs/vfs.c
TFT/src/User/Fatfs/myfatfs.c
TFT/src/User/Menu/Print.c

**BUGFIXES:**
* Fixed a bug reported in #2300: Missing thumbnail icon's when going back/forth pages.
* Fixed #2307
fixes #2307 (bug found and solved by @rondlh)
**PR STATE:** Ready to merge

Fixed #2300

---

TFT/src/User/Menu/Fan.c

BTT or MKS TFT
This PR fixes the odd behaviour of the Fan menu.
Fixes #2319

Fix Fan menu odd behaviour

---

Copy to SD Card root directory to update/Language Packs/language_br.ini
Copy to SD Card root directory to update/Language Packs/language_cz.ini
TFT/src/User/API/Language/language_br.h
TFT/src/User/API/Language/language_cz.h

Completion of the Czech translation
Completion of the Brazilian translation

Czech translation + BR

---

TFT/src/User/Menu/Tuning.c

Disabled Home Offset icon, M206 command isn’t available for Delta printers.

Disable Home Offset for Delta printers

---

TFT/src/User/API/menu.c
TFT/src/User/Hal/STM32_USB_HOST_Library/Usr/src/usb_bsp.c
TFT/src/User/Variants/pin_GD_TFT35_V3_0.h
platformio.ini

* fix compiled warning
* fix Invalid character in title bar when startup
* the reason of stability is to modify the USB Library of GD temporarily

GD32 USB Lib

---

TFT/src/User/API/parseACK.c
TFT/src/User/Menu/BLTouch.c

BTT or MKS TFT
PR #2459 had a typo which lead to a bug. This PR is a fix for it.

Post merge fix for PR #2459

---

TFT/src/User/API/menu.h
TFT/src/User/Menu/PrintingMenu.c

* fix frozen bug in printingMenu

fix frozen bug in printingMenu

---

TFT/src/User/API/Printing.c
TFT/src/User/API/Printing.h
TFT/src/User/API/menu.c
TFT/src/User/Menu/PrintingMenu.c

- Fix: title display on the popup dialog after #2447.
~- Fix: progress bar not updating if progress is 100% after #2404.~
- Simplify the progress bar display code and remove redundant variables.
- cleanup and remove duplicate lines.
Fixes: #2476

fix title draw on popup dialog

---

TFT/src/User/API/Language/language_hu.h
TFT/src/User/API/Settings.h

Just a simple HU language update for the newly created language elements.

HU language update

---

TFT/src/User/Menu/LevelCorner.c

**BUGFIX:**
* Fixed missing display of probe values in L Corner menu when **start** button was used: In case the start button was used, only the value for the last point was properly displayed (for the first three points, values were not updated). The bug was introduced in last merged PR #2517.

Fixed bug in L Corner menu

---

.github/workflows/buildBinary.yml

Use package emoji in "Update prebuilt binaries and config" commit message for easier identification.
Example:
Easily identify/find auto-commits

Tweak "Update prebuilt binaries and config" commit message

---

Copy to SD Card root directory to update/Language Packs/language_cz.ini
TFT/src/User/API/Language/language_cz.h

Czech translation update.

---

Copy to SD Card root directory to update/Language Packs/language_cz.ini
TFT/src/User/API/Language/language_cz.h

CZ translation

---

TFT/src/User/API/Printing.c
TFT/src/User/API/Printing.h
TFT/src/User/API/RRFParseACK.cpp
TFT/src/User/API/RRFParseACK.hpp
TFT/src/User/API/comment.c
TFT/src/User/API/interfaceCmd.c
TFT/src/User/API/parseACK.c

- BTT or MKS TFT
- parse RRF print percentage message
- those using RRF
Fixes #2547

RRF progress fix

---

Copy to SD Card root directory to update/config.ini
Copy to SD Card root directory to update/config_rrf.ini
README.md
TFT/src/User/API/UI/GUI.h
TFT/src/User/API/menu.c
TFT/src/User/API/parseACK.c
TFT/src/User/Configuration.h
TFT/src/User/Menu/PersistentInfo.c
TFT/src/User/Menu/StatusScreen.c
TFT/src/User/config.ini

Some minor bugfixes + cleanup on configuration files.
fixes #2544
fixes #2545

Minor bugfixes + cleanup on configuration files

---

.github/workflows/buildBinary.yml
README.md
TFT/src/User/API/Printing.c
TFT/src/User/API/Printing.h
TFT/src/User/API/RRFParseACK.cpp
TFT/src/User/API/UI/GUI.c
TFT/src/User/API/UI/ui_draw.c
TFT/src/User/API/UI/ui_draw.h
TFT/src/User/API/comment.c
TFT/src/User/API/interfaceCmd.c
TFT/src/User/API/parseACK.c
TFT/src/User/Configuration.h
TFT/src/User/Menu/Print.c
TFT/src/User/config.ini
TFT/src/User/config_rrf.ini

- Improved performance on GUI_DispOne() function: With the exception of text requiring transparency (GUI_TEXTMODE_TRANS), each character in a text is now displayed in a char by char mode (an LCD window is used) instead of pixel by pixel mode (an LCD window made by only one pixel). The improved performance is present in any menu displaying alternating text (e.g. Printing menu, Status menu etc...) and on any TFT variant.
Affected files are:
- GUI.c
- ui_draw.c
- ui_draw.h
- Source for `config_rrf.ini` maintained on folder `TFT\src\User`: As it is for `config.ini` and `Language Packs`, `config_rrf.ini` is now maintained on project source folder `TFT\src\User` and copied to distribution folder `Copy to SD Card root directory to update` during the distribution files update …

Improved GUI performance

---

coding_standard.md

Fix "coding_standard.md" to respect its own standards. (How ironic that it wasn't...)

Fix "coding_standard.md" to respect its own standards

---

TFT/src/User/Menu/Extrude.c

Fix speed change not working in Extruder control screen.

Fix extruder speed change

---

TFT/src/User/API/FlashStore.c
TFT/src/User/API/comment.c
TFT/src/User/API/menu.c

- Remove unnecessary variable declaration.
- Optimize comment parsing in comment.c and remove duplicate lines.
-  Cleanup loopCheckBackPress function in menu.c file.

Cleanup and remove duplicate code

---

README.md

Shameless self-plug of my plugin that provides integration of this firmware for OctoPrint.
:moneybag: :cake: :ice_cream: 
Maybe the following:
- https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2944
- https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2486

Added link to octoprint plugin
