- TFT/src/User/API/UI/GUI.c
- TFT/src/User/API/UI/GUI.h
- TFT/src/User/Menu/BabyStep.c
Enable Mode and Right Align option for GUI DIsp Float
> Enable Mode and Right Align option for GUI DIsp Float

- TFT/src/User/API/Language/Language.c
- TFT/src/User/Hal/LCD_Init.c
- TFT/src/User/Hal/stm32f10x/Serial.c
- TFT/src/User/Hal/w25qxx.h
- TFT/src/User/Menu/BabyStep.c
- TFT/src/User/Menu/Extrude.c
- TFT/src/User/Menu/Fan.c
- TFT/src/User/Menu/Heat.c
- TFT/src/User/Menu/Home.c
- TFT/src/User/Menu/MainPage.c
- TFT/src/User/Menu/Mode.c
- TFT/src/User/Menu/Move.c
- TFT/src/User/Menu/PowerFailed.h
- TFT/src/User/includes.h
Change #include filenames to match capitalization of actual files.
Required to compile on non-Microsoft operating systems.
> Merge and fix includes.

- TFT/src/User/API/UI/ST7920_Simulator.c
- TFT/src/User/Configuration.h
"LCD12864 Simulator" is now definable in `Configuration.h`.
> User-Definable "LCD12864 Simulator" Text

- TFT/src/User/API/UI/ST7920_Simulator.h
- TFT/src/User/Configuration.h
- TFT/src/User/Hal/stm32f10x/lcd.h
- TFT/src/User/Menu/Popup.c
Users can now change the 12864 mode background & font colors in `Configuration.h`. The black background looks the best due to letterboxing.
Current color options from lcd.h: BLACK, BLUE, BROWN, BRRED, CYAN, GBLUE, GRAY, GREEN, MAGENTA, RED, WHITE, YELLOW
Also, I removed duplicate colors since `BRED` = `MAGENTA` (both were `0XF81F`) & `GRED` = `YELLOW` (both were `0XFFE0`).
> User-Definable 12864 Mode Colors & Color Cleanup

- TFT/src/User/API/UI/ST7920_Simulator.c
- TFT/src/User/Menu/Mode.c
fix variable type, from char* to uint8*
> Fix string varible type warning

- platformio.ini
This PR fixes the "env_default" depreciation warning with PlatformIO 4.0.
> env_default => default_envs

- TFT/src/User/Configuration.h
Changes the default "LCD12864 Simulator" text from `WHITE` back to `GREEN`.
Highlighted options are now visible when selecting TFT/12864 modes.
> Green Default 12864 Text

- TFT/src/User/Menu/leveling.c
manual leveling buttons are now displayed only if ABL is turned off in the configuration file
> Changed leveling menu

- TFT/src/User/API/UI/ST7920_Simulator.c
- TFT/src/User/Configuration.h
- TFT/src/User/Menu/Mode.c
You can now simply comment out `ST7920_BANNER_TEXT` to disable the "LCD12864 Simulator" text at the top of 12864 mode.
It's now easier to disable the "LCD12864 Simulator" text.
> ST7920_BANNER_TEXT can be disabled

- TFT/src/User/Configuration.h
This PR splits 12864 & TFT mode settings up in Configuration.h and cleans up some comments.
Locate settings easier.
> Reorganize Configuration.h

- buildroot/boards/STM32F103VC.json
- buildroot/boards/STM32F105RC.json
- buildroot/scripts/stm32f10x_0x3000_iap.py
- buildroot/scripts/stm32f10x_0x6000_iap.py
- buildroot/scripts/stm32f2xx_0x8000_iap.py
Resolves https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/126
This is a temporary low-level solution that works with previous PIO Core versions and will work with the future. However, there is a better way to do this via `board_build.ldscript`. There is a bug in ST STM32 dev/platform which overrides user custom LD Script declared in `board_build.ldscript` way. We will fix it soon. So, you can simplify your configuration later.
Sorry for the issue.
> Override default LD Script using LINKFLAGS build scope

- TFT/src/User/Configuration.h
We don't really need to have the "LCD12864 Simulator" banner enabled by default since users will know which mode they are in.
Uncomment `ST7920_BANNER_TEXT` to enable & you can customize text as before.
Cleaner default UI.
> Disable "LCD12864 Simulator" Banner by Default

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Creating new bug reports, feature requests, and pull requests will now use templates.
Standardize requested info from users/PRs:
**New bug report/feature request:**
**New PR:**
> Add bug report, feature request, and PR templates

- TFT/src/User/API/parseACK.c
- TFT/src/User/Configuration.h
- TFT/src/User/Menu/Fan.c
- TFT/src/User/Menu/StatusScreen.c
- platformio.ini
Description:
This adds the ability to display the fan speed as a percentage rather than the pwm value. It also adds parsing of a fan speed token in the temperature output (F0). A feature for adding the fan speed to the temperature output in marlin has been submitted.
Benefits
Showing the fan speed as a percentage is more user friendly than a number from 0 - 255. Adding the fan speed token parsing allows for the fan speed to be updated when gcode is being sent from another host (eg octoprint)
> Adds display of fan as a percentage

- TFT/src/User/Configuration.h
- TFT/src/User/Menu/PowerFailed.c
if miniUPS is used, printer will raise z axis in power failed, so dont need raise again before resume printing
> add miniUPS support in power failed

- TFT/src/User/variants.h
> fix TFT35 V3.0 power supply control pin, from wrong PA12 to correct PC12

- TFT/src/User/Configuration.h
- TFT/src/User/Menu/Printing.c
Description: adds a define in Configuration.h for the gcode to run at the end of a canceled print
Benefits: better user experience and code management to have custom gcode run at the end of a print instead of directly modifying the abortPrinting function in Printing.c
Related Issues: N/A
> Added define for cancel print gcode

- TFT/src/User/API/UI/list_item.c
- TFT/src/User/Menu/FeatureSettings.c
- TFT/src/User/Menu/Move.c
- TFT/src/User/Menu/StatusScreen.c
- TFT/src/User/Menu/StatusScreen.h
- TFT/src/User/Menu/menu.c
- TFT/src/User/Menu/menu.h
- fix status screen flicker due to changes after cleanup commit 577635c
- Fix missing negative sign in move z command in move menu.
- Fix bugs in list mode settings page and improve list display.
> Fix status screen flicker after cleanup commit & Fix issues with list mode in setting

- TFT/src/User/API/Language/Language.c
- TFT/src/User/API/Language/Language.h
- TFT/src/User/API/Language/language_am.h
- TFT/src/User/API/Language/language_cn.h
- TFT/src/User/API/Language/language_cz.h
- TFT/src/User/API/Language/language_de.h
- TFT/src/User/API/Language/language_du.h
- TFT/src/User/API/Language/language_en.h
- TFT/src/User/API/Language/language_es.h
- TFT/src/User/API/Language/language_fr.h
- TFT/src/User/API/Language/language_it.h
- TFT/src/User/API/Language/language_jp.h
- TFT/src/User/API/Language/language_pl.h
- TFT/src/User/API/Language/language_pt.h
- TFT/src/User/API/Language/language_ru.h
- TFT/src/User/API/Language/language_sk.h
- TFT/src/User/API/extend.c
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/More.c
- TFT/src/User/Menu/Printing.c
- TFT/src/User/Menu/Printing.h
enable detection of M0/M1 command when printing from SD card on TFT controller and prevent 'paused for user' prompt (issue #211)
**requires `EMERGENCY_PARSER` to be enabled in marlin firmware**
> Intercept M0/M1 command when printing from SD card on TFT controller

- .github/workflows/buildTest.yml
- platformio.ini
Minor change, just for completeness; adding BIGTREE_TFT28_V3_0 target to build test configuration.
build test for all targets
> Adding BIGTREE_TFT28_V3_0  target to build test

- .github/workflows/buildTest.yml
- platformio.ini
Include MKS TFTs in build test
More thorough testing of supported builds
None
CCing @darkspr1te as they contributed the original code for these TFTs.
> Include MKS TFTs in build test

- TFT/src/User/Menu/FeatureSettings.c
* Steps to reproduce the bug
"Setting->Feature->down->down"
When you go to the last page of Feature, `settingPage[]` arry will out of bound, and damage other important data in RAM, then you go to "Gcode" terminal interface，touch screen will crash.
> fix settingPage array out of bound bug, cause some crash

- TFT/src/User/API/parseACK.c
- TFT/src/User/API/parseACK.h
1. Adjust the position of the ACK string parsing, and sort it from top to bottom according to the possible frequency of occurrence
2. fixed can only get TMC X driver current after #401 , #401 parse each `'\n'` segment separately,
```
X driver current: 580
Y driver current: 580
Z driver current: 580
E driver current: 650
ok
```
each axis has a `'\n'` which means there is only one axis current in the same segment
> fix M906 TMC Current 

- TFT/src/User/API/Language/Language.c
- TFT/src/User/API/Language/Language.h
- TFT/src/User/API/Language/language_am.h
- TFT/src/User/API/Language/language_cn.h
- TFT/src/User/API/Language/language_cz.h
- TFT/src/User/API/Language/language_de.h
- TFT/src/User/API/Language/language_du.h
- TFT/src/User/API/Language/language_en.h
- TFT/src/User/API/Language/language_es.h
- TFT/src/User/API/Language/language_fr.h
- TFT/src/User/API/Language/language_it.h
- TFT/src/User/API/Language/language_jp.h
- TFT/src/User/API/Language/language_pl.h
- TFT/src/User/API/Language/language_pt.h
- TFT/src/User/API/Language/language_ru.h
- TFT/src/User/API/Language/language_sk.h
- TFT/src/User/Menu/FeatureSettings.c
- TFT/src/User/Menu/Popup.c
- TFT/src/User/Menu/Popup.h
Able to reset the customer setting from the menu. It will bring a waring dialog to ensure to reset by mistake.  So no need to add a file to sd-card to reset the settings. Ignore lcd mode only if you reset all settings and to show the info dialog. Otherwise, it won't show if you currently in CLEAN_MODE_SWITCHING_SUPPORT.
> PR-#Resetting all settings from within the UI menu.

- TFT/src/User/Menu/Printing.c
When print is finished on unified menu, the screen still show the 'Stop' button (which is not logical) and when you click on it it will go to the previous screen.
Now the button decoration is changes to 'Back'.
* Visually showing on the screen that the print is finished
* Showing real effect of the button
> Update 'Stop' button to 'Back' when print is finished

- TFT/src/User/API/LCD_Encoder.c
- TFT/src/User/API/UI/touch_process.c
- TFT/src/User/API/flashStore.c
- TFT/src/User/Hal/LCD_Init.c
- TFT/src/User/Hal/LCD_Init.h
- TFT/src/User/Hal/stm32f10x/timer_pwm.c
- TFT/src/User/Hal/stm32f10x/timer_pwm.h
- TFT/src/User/Hal/stm32f2xx/timer_pwm.c
- TFT/src/User/Hal/stm32f2xx/timer_pwm.h
- TFT/src/User/Menu/FeatureSettings.c
- TFT/src/User/Menu/Mode.c
- TFT/src/User/Menu/Settings.c
- TFT/src/User/Menu/Settings.h
- TFT/src/User/Menu/ledcolor.c
- TFT/src/User/Menu/ledcolor.h
- TFT/src/User/SanityCheck.h
- TFT/src/User/Variants/pin_MKS_TFT32_V1_4.h
- TFT/src/User/Variants/pin_TFT24_V1_1.h
- TFT/src/User/Variants/pin_TFT35_E3_V3_0.h
- TFT/src/User/Variants/pin_TFT35_V1_0.h
- TFT/src/User/Variants/pin_TFT35_V2_0.h
- TFT/src/User/Variants/pin_TFT35_V3_0.h
- TFT/src/User/Variants/pin_Template.h
- TFT/src/User/Variants/variants.h
- TFT/src/User/includes.h
- TFT/src/User/main.c
- TFT/src/User/os_timer.c
* add common PWM Hal library for LCD back light control
* modify "LED_color_PIN" to "LCD_COLOR_PIN" (Macro definition all caps principle)
* add Marlin mode and backlight control macro switch in feature settings menu
* change os timer from tim4 to basic tim7, free tim4 for PWM backlight control
> improve LCD led control, add common PWM Hal library

- TFT/src/User/Menu/ledcolor.h
LED colors are in GRB format, not RGB.
Correct LED colors.
https://github.com/bigtreetech/BTT-TFT35-E3-V3.0/issues/6
Note: Even pure white (`0x00FFFFFF`) has a green tinge to them, so I think these LEDs are just green heavy.
> Fix Orange and Indigo LED colors

- TFT/src/User/Menu/leveling.c
Always home before [Probe Repeatability Test](https://marlinfw.org/docs/gcode/M048.html) (run G28 before M48).
Users won't have to home manually before running Probe Accuracy Test through the TFT's ABL menu if the hotend position is unknown.
Fixes https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/549
Tested on a TFT35 V3 & TFT35 E3 V3.
> Always home before Probe Repeatability Test

- TFT/src/User/Menu/Mode.c
Prevent boot screen from showing when Mode is changed on Variants with dual-mode.
this allows for a quick change from ST7920 to Touch Mode.
The boot screen will show only when the device is powered ON.
> Prevent boot screen from showing when Mode is changed on Variants with dual mode.

- TFT/src/User/API/extend.c
- TFT/src/User/Hal/STM32Fxx_Pins.h
- TFT/src/User/Hal/stm32f2xx/GPIO_Init.h
- TFT/src/User/Menu/Parametersetting.c
- TFT/src/User/Menu/Print.c
- TFT/src/User/Menu/Printing.c
* fix filament runout default level, if not insert sensor,  will pup up "filament runout" immediately when start printing
* fix "M190" & "M109" don't wait temperature reached in printing.
> fix filament runout init / gcode queue for M109 & M190

- TFT/src/User/API/parseACK.c
Repetier-Firmware ack of "M105\n" is "ok 0\n T:20/0\n", "ok" and "T:20" are not on the same line， so temperature need separate parse with "ok"
#552
> fix Repetier-Firmware compatibility

- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/Popup.c
- TFT/src/User/Menu/Popup.h
This is useful for setups that need to pause for a leveling probe to be attached on ABL. My uses PAUSE_BEFORE_DEPLOY_STOW and if it doesn't send M108 the printer is hard frozen.
There is not too much to this change. Now when "paused for user" comes in and the machine is not printing a pop up comes up to let the user hit OK to continue. 
This makes the screen more usable. This way people don't get into a situation where the machine is waiting for a button press without a way to get one.
None that I am aware of. Why does M108 need to be sent using 
`Serial_Puts(SERIAL_PORT, "M108\n");`
The same code is found in Printing.c line 317. Must store did not result in the command ever being sent. 
Notably sending M0 then M108 through the screen's little console doesn't register as an OK. That …
> Code to handle pause outside of printing

- TFT/src/User/Configuration.h
The Idle Timer options had 4 listed twice, so this PR updates the comments to show 1-8 correctly.
Idle Timer options/comment is now correct.
Fixes #580
> Update Idle Timer comment

- .editorconfig
Ensure *.ini files are saved with UTF-8 encoding.
With https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/526 hopefully getting merged soon, this ensures the `config.ini` file will be saved with the correct encoding.
None
Please install the [EditorConfig plugin](https://github.com/editorconfig/editorconfig-vscode). This will keep code tidy and ensure proper file encoding.
> Ensure INI files are saved with UTF-8 encoding

- TFT/src/User/API/boot.c
Replace second "Updating Logo" text with "Updating Icons".
Correct text is displayed while updating TFT firmware.
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/464#issuecomment-619616901
> Fix "Updating Icons" typo

- TFT/src/User/API/LCD_Encoder.c
- TFT/src/User/API/Language/language_cz.h
- TFT/src/User/API/parseACK.c
Correction for two extruders
For two axtruders, the values are not displayed:
Steps per mm
Max feed Rate
Max Acceleration
viz.
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/556
Correction of syntax in the file LCD_Encoder.c 
Fixes an issue that arises during compilation in the LCD_Encoder.c file
CZ translation correction
> Correction for:  two extruders, Sintaxe LCD_Encoder.c, CZ translation

- TFT/src/User/API/parseACK.c
- TFT/src/User/API/parseACK.h
- TFT/src/User/Configuration.h
- TFT/src/User/Menu/Print.c
- TFT/src/User/Menu/Printing.c
- TFT/src/User/Menu/Settings.c
- TFT/src/User/Menu/Settings.h
- TFT/src/User/Menu/menu.c
- With this update, the TFT firmware will be able to auto-detect Onboard SD Card with M115 starting from Marlin Bugfix 2.0.x date: 2020-04-27.
- Enable PRINT_CANCEL_GCODE by default and change PRINT_CANCEL_GCODE behaviour to be sent only when printing from TFT's SD card and USB flash disk to avoid duplicate Cancel G-codes when printing from Onboard SD card.
> Add auto-detect On-board SD Card via M115 and change PRINT_CANCEL_GCODE behaviour to be sent only when printing from TFT's SD card

- TFT/src/User/Menu/BabyStep.c
Babysteps are not working correct while printing over tft/rs232. Maybe the rs232 buffer is too busy.
Changed command from StoreCmd to mustStoreCmd. The Encoder did not work either. Also the Save Icon is obsolete, there is nothing to save..
This bug was found by nicolas81. Please see bigtreetech#584
> Babystep fix

- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/Printing.c
- TFT/src/User/Menu/Printing.h
Add better support for listing files / start print / delete file of TFT SD and TFT USB, uploading file to printer SD and TFT capabilities
More features allowing listing files / start print / delete file of TFT SD and TFT USB
by adding a hook when SD: or U: is added in front of file path
e.g.:
`M20 SD:` List TFT SD files
`M20 U::` List TFT USB files
```
M20 SD:
Begin file list
/MKS.CUR/
End file list
ok
M20 U:
Begin file list
/eclipse/
/Arduino - 1.6.9 -Due 1.6.8/
/GitHub/
/ld5110/
End file list
ok
```
this apply to: 
* M23 and M24 to print file from TFT SD and TFT USB, 
* M25 to pause print file from TFT SD and TFT USB 
* M27 to get print status from print file from TFT SD and TFT USB
* M30 to delete file from  TFT SD and TFT USB 
* M524 to abort printing  from TFT SD and TFT USB
* M115 …
> Add better support for Printer SD / TFT SD /TFT USB from ESP3D and other extern prog

- TFT/src/User/Menu/Heat.c
Fix for wrong heater indexes issue that caused last heater to be ignored in some functions
M109 will work as intended when printing from TFT
None that I know of.
> Fix heater indexes

- TFT/src/User/Menu/Printing.c
Fix misplaced send_cancel_gcode in abortPrinting
Enabled Cancel Gcode works now as expected, before it was not executed 
Cancel Gcode doesn´t work on TFT-SD and U_DISK
> Fix send_cancel_gcode in abortPrinting

- TFT/src/User/Menu/Mode.c
send "M105" 1s later not startup, because of mega2560 will be hanged when received data at startup.
#552
> fix mega2560 "no printer attached!"

- TFT/src/User/API/config.c
All supported screens.
In the config.c file the code reading the marlin_fullscreen parameter from the config.ini file is missing.
Defining the marlin_fullscreen parameter via the config.ini file
> Fix the marlin_fullscreen parameter in config.ini doesn't work.

- TFT/src/User/Menu/ledcolor.c
Changed knob LED timing from 0.4us to 0.35us to correct colors of the knob on the TFT35 E3
According to the WS2812 documentation 0.35us is the right timing to set here.
On some TFT35 E3 boards release 26.1 broke the knob lighting. This is caused by different tollerance of the "0" timing of different WS2812 LEDs. This PR restores the ability to set colors to the knob leds or to switch them off.
Resolves #696
> Restore the ability to change knob colors on TFT35 E3 v3.0, broken in release 26.1

- TFT/src/User/Fatfs/myfatfs.c
- TFT/src/User/Hal/STM32_USB_HOST_Library/Usr/src/usbh_usr.c
- TFT/src/User/Menu/Print.c
fixed u disk can't preview model function after #544
This is because before `f_open` gcode file, the BMP file of the preview icon will be read first, which makes a lot of `f_ read(USBH_ MSC_ Read10)` but did not call `USBH_Process`, which causes USB to pile up a large number of USB tasks.
This PR adds the judgment on the current state of USB  in `f_ read(USBH_ UDISK_ Read)`. If USB is not in idle state, calling `USBH_Process ` first,  and read/write until idle.
> fix u disk preview model function

- TFT/src/User/Menu/PowerFailed.c
u disk write is ok after #746, so enable `resume printing after power failed ` function for u disk
> enable PLR for u disk

- TFT/src/User/Menu/Heat.c
- TFT/src/User/Menu/StatusScreen.c
Improvements for Unified Menu logic:
1. From the Status Screen we can go to nozzle or bed management. How it works now: we get another menu - Unified Heat Menu. And we must to go more deeper before reach the desired tool (nozzle or bed). But I believe that user want to get a corresponding tool immediately. So I made a direct way to it. You can compare this logic with the fan menu. It can be reached directly from the Status Screen. Now the same behavior (direct way) for the nozzle and the bed.
2. Again about nozzle/bed menus. When the user comes to the desired menu he got a Heat Menu with unpredictable target. It can be a nozzle or a bed, in depending of what was …
> Improve heat menu logic

- TFT/src/User/API/Gcode/gcode.c
Troubleshooting when printing from Onboard SD.
If no SD card is inserted, and I choose to print from the SD onboard, the display will freeze
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/725
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/704
resolves #725
> Onboard SD not inserted

- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/Configuration.h
This is an improvement / new feature.
Prusa firmware and Prusaslicer support an advanced pause M601.
Prusaslicer can add this to the gcode to pause at certain heights e.g. insert sthg or change filament.
Marlin does not implement M601 at the moment and 
Marlins advanced pause feature (M600) only works with LCD / TFT in Marlin Mode.
* support this advanced pause gcode for prints from sdcard & usb
* enable advanced pause  for serial-only connected displays
maybe #758
> Adding emulated M601

- TFT/src/User/Menu/ScreenSettings.c
The uint8_t cur_item is declared but not initialized in two functions, which may lead to undefined behavior. As per the ISO C18 standard: "If an object that has automatic storage duration is not initialized explicitly, its value is indeterminate (section 6.7.9)."
Remove warning when compiling.
Not applicable.
> Fix warning: 'cur_item' may be used uninitialized in this function

- TFT/src/User/API/interfaceCmd.c
Rotary encoder BTT TFT
When using the rotary encoder after https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/41a11faf2384957114bb23421895fa861b6458d4 the values for fan speed, speed and flow were getting stuck in a loop as they were updated from both the respective menu and the command queue via g-code parsing.
Fix loop updating values via menu and command queue.
Fixes https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/826
> Fix duplicate update of speeds and flow #826

- TFT/src/User/API/interfaceCmd.c
Fixed automatic update of fan speed to status screen when printing if the "Serial_always_on: 0" option is activated
#827 was a bad fix which produced problems with updating values on the status screen
replace it patch #840, #846, #847
resolves #843
> Fixed automatic update of fan speed

- TFT/src/User/API/extend.c
fix always Filament runout popup when runout once time, altough the filament have beed reinserted
> fix always Filament runout popup when runout once time

- TFT/src/User/API/Settings.c
- TFT/src/User/API/UI/Numpad.c
- TFT/src/User/API/UI/Numpad.h
- TFT/src/User/Menu/BabyStep.c
Fixed entering values via numpad if the value contains 5 digits - resolves #867
typo correction  - mentioned #866
Add a Save button to the BabyStep menu  - mentioned #869
> Numpad repair

- .editorconfig
Use LF line endings as most files are already saved with this formatting.
Current line endings aren't re-written with CRLF line endings on every save.
Tested (again) on a fresh Windows 10 & macOS installs with the latest VSCode (1.47.3 as of this PR) + [EditorConfig plugin](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig).
None.
> Use LF line endings

- Copy to SD Card root directory to update - Unified Menu Material theme/config.ini
- Copy to SD Card root directory to update/config.ini
- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/UnifiedMove.c
- TFT/src/User/config.ini
- TFT/src/User/main.c
the `XPT2046_Init()` and `knob_LED_Init()` function is moved before` OS_TimerInitMs()`
Because touch and knob LED will be called in the timer interrupt, so the initialization must be completed before calling
#918
> fix hang when updating

- TFT/src/User/Menu/menu.c
the `bk_color `value is uncertain when `text_mode == GUI_TEXTMODE_TRANS`, so it will freeze if `bk_color ` beyond `LCD_COLOR_COUNT`
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/939#issuecomment-671024642
> fix some freeze in showLiveInfo

- TFT/src/User/Menu/More.c
- TFT/src/User/Menu/PrintingMenu.c
Addition of the BabyStep button to the More menu.
If a file generated with Cura plagin is printed to create an icon, the Baby Step button is missing in the PrintingMenu.
resolves #943 
Added BabyStep button to More menu.
Added BabyStep button to PrintingMenu, even when a model preview is displayed. Click on the model to display BabyStep
> Addition of the BabyStep button

- TFT/src/User/Configuration.h
UBL (AUTO_BED_LEVELING_UBL) is enable by default and for people use AUTO_BED_LEVELING_BILINEAR or other it's not good for leveling settings.
With this parameters set to auto-detect, all is working fine.
See issue https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/985
> Fix UBL enable by default

- TFT/src/User/API/Gcode/gcode.c
- TFT/src/User/API/Gcode/gcode.h
- TFT/src/User/API/Temperature.c
- TFT/src/User/API/extend.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/More.c
- TFT/src/User/Menu/PrintingMenu.c
- TFT/src/User/Menu/menu.c
* cleanup `requestCommand` code, Flash use reduced 100 bytes, Global RAM use reduced 470 + bytes
* M21 start Magic “SD” modify to "SD Card ", because error Magic "No SD Card" will be parsed to start Magic
> fix & cleanup onboard sd print

- TFT/src/User/API/parseACK.c
- TFT/src/User/Configuration.h
If the Mixing_extruder option is selected in Marlin, the printer uses two extruders, but reports only one extruder at the M115 command.
The FW display overwrites the manually entered number of extruders with what the printer reports.
This option disables the value override, and the value specified in Configuration.h is used
resolves #1055
resolves #1043
> Option for Mixing_extruder

- .github/lock.yml
- .github/stale.yml
- TFT/src/User/API/BabystepControl.c
- TFT/src/User/API/LCD_Encoder.c
- TFT/src/User/API/Settings.c
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/Babystep.c
- TFT/src/User/Menu/Home.c
- TFT/src/User/Menu/Leveling.c
- TFT/src/User/Menu/MachineSettings.c
- TFT/src/User/Menu/Mode.c
- Change `ENC_ACTIVE_SIGNAL` logic to disable encoder in Marlin firmware when TFT is not in Marlin mode. Details in https://github.com/MarlinFirmware/Marlin/pull/19796
- clean-up
- Add stale bot config to manage old abandoned issues. @bigtreetech Needs installing stale app for the repository from here: https://github.com/apps/stale
This will fix #680 after https://github.com/MarlinFirmware/Marlin/pull/19890 is merged in marlin firmware.
Resolves #1206 , Resolves #1045
> Change ENC_ACTIVE_SIGNAL logic to disable encoder in Marlin firmware when TFT is not in Marlin mode.

- TFT/src/User/Language Packs/language_hu.ini
A language_en.ini was left out. There’s so much of it already that I didn’t notice. I don't know why so much. But there must be a reason.
By: AntoszHUN
> It was missed

- Copy to SD Card root directory to update - Unified Menu Material theme/config.ini
- Copy to SD Card root directory to update/config.ini
- TFT/src/User/API/parseACK.c
- TFT/src/User/config.ini
Fix to display M117 messages send by Octoprint plugin like DisplayLayerProgress in info area.
resolves #494
resolves #1050
> Fix to display M117 messages in info area

- TFT/src/User/API/Settings.c
- TFT/src/User/Menu/SendGcode.c
- TFT/src/User/Menu/SendGcode.h
On the gcode message display interface of the terminal, touch the upper half screen to turn pages up and touch the lower half screen to turn pages down.
```
screen:
exit botton
+------------------------+
|                        |
|        page up         |
|                        |
+------------------------+
|                        |
|        page down       |
|                        |
+------------------------+
```
TFT35 E3 , TFT 43 , TFT 50 FLASH overflowed about 300 bytes
> Supports Scroll gcode messages in terminal

- Copy to SD Card root directory to update - Unified Menu Material theme/config.ini
- Copy to SD Card root directory to update/config.ini
- TFT/src/User/API/Gcode/mygcodefs.c
- TFT/src/User/API/Temperature.c
- TFT/src/User/API/Temperature.h
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/Heat.c
- TFT/src/User/Menu/Mode.c
- TFT/src/User/Menu/Print.c
- TFT/src/User/Menu/TuneExtruder.c
- TFT/src/User/config.ini
- TFT/src/User/main.c
After printing from the onboard SD, the bed and nozzle temperatures are not updated until they reach the target temperature.
This adjustment solves it.
Adding code "M155 S1" to start G-code does not work.
Adding a code to the start code in Cura also does not work.
First the heating is started and only then the start code is activated.
Therefore, the values on the display are not updated until the target temperature is reached.
resolves #1127
resolves #1225
resolves #1070
Add a comment to Config.ini, with information about the required settings in Marlin
PS:
When printing from the onboard SD, there is still a problem and detecting the print height. If someone knew the solution, it would be good to add it as well.
If https://github.com/MarlinFirmware/Marlin/pull/18427 is merged, it could be …
> Temperature update when printing from onboard SD

- TFT/src/User/API/interfaceCmd.c
None
M18/M84 commands are used to disable steppers, however they also are used to set the stepper inactivity timeout:
M18 S60; Set the stepper inactivity timeout to 1 minute
When only setting the timeout, steppers are not disabled. 
Thus ,if the print is paused, the printhead would not move to a safe spot as the coordinates would be considered as unknown.
To fix this, I added a simple test, in the case a M18/M84 command is seen, it checks for the arguments and if only S is specified, it will not mark coordinates as unknown as it is not needed.
In the eventuality a M18/M84 S<timeout value> was sent during a print, the next pause command would not move the print head to a safe spot.
This commit fixes this behavior.
> Avoid marking coordinate as unknown when parsing a M18/M84 S<timeout>

- Copy to SD Card root directory to update/config.ini
- TFT/src/User/config.ini
A general cleanup on config.ini file:
* Title on section part ALWAYS uses capital letters for any word
* Title on paramter part ALWAYS uses capital letters for any word
* Title on paramter part NEVER provides any comment/description
* A parameter comment/description is provided ONLY on paramter body part
* Parameter qualifiers such as:
* Format
* Unit
* Value range
* Options
are ALWAYS provided on parameter body part when neeeded (e.g. °C, mm, seconds etc...)
**PR STATE:**
* **FINAL:** Ready to be merged with BTT main branch:
\
\
\
SECTION PART:
\#--------------------------------------------------------------------
\# <TITLE> (e.g. Supported TFT Variants)
\#--------------------------------------------------------------------
\# <comment/description> …
> config.ini cleanup

- TFT/src/User/API/config.c
- TFT/src/User/API/coordinate.c
- TFT/src/User/Menu/Babystep.c
- TFT/src/User/Menu/MBL.c
- TFT/src/User/Menu/PrintingMenu.c
- TFT/src/User/Menu/TuneExtruder.c
just a minor cleanup (not committed on my just merged PR)
fixes #1386
> minor cleanup

- TFT/src/User/API/ProbeHeightControl.c
- TFT/src/User/API/SpeedControl.c
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/Configuration.h
- TFT/src/User/Menu/Speed.c
Need to add M575 P1 S2 B115200 in the config.g of the sd card of the duet motherboard.  
ReprapFirmware Versions: 3.1.1  
This is achieved by enabling the Marlin compatibility mode of the ReprapFirmware.   
Realizes function:  
TFT printing,  
Control of extrusion and bed temperature,  
CNC fan,   
Speed and flow control etc.  
Which can completely replace Panel Due.  
Due to the lack of \n when the Reprapfirmware responds to M20, it cannot read the onboard sd card normally.  
Some advanced settings of marlin different from reprap are not available.
> Compatible with RepRapFirmware

- TFT/src/User/Configuration.h
`MDOE SERIAL_TSC` => `MODE_SERIAL_TSC`
Correct documentation.
None. Found while rebasing my config to the latest version.
> Fix Default Mode Typo

- TFT/src/User/Menu/ABL.c
Adds more Mesh fill commands since a single g29 p3 is not enough for larger meshes. (10x10) tested
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1281
> Fill in more points on the mesh

- .github/workflows/buildBinary.yml
- .github/workflows/buildTest.yml
1. Copy `config.ini` when building binaries so the version located in `Copy to SD Card root directory to update/` won't have to be updated each time the main version in `TFT/src/User/` is updated.
2. Ignore changes to the following files/folders for automatic binary/config uploads:
- .devcontainer/
- .github/
- Bootloader/
- Copy to SD Card root directory to update/
- images/
- readme/
- *.md
3. Ignore changes to the following files/folders for build tests:
- Bootloader/
- Copy to SD Card root directory to update/
- images/
- readme/
- *.md
Tagging @Codel1417 as they introduced automatic binary uploads in #1450
Automate updating `config.ini` in the "Copy to SD Card" folder and only run CI when needed & don't upload new binaries when readmes/non-code changes are committed.
None.
> Improve "Build Binaries" and "Build Test" GitHub Actions

- TFT/src/User/API/boot.h
Fix filenames to work on TFT24 to reset settings after firmware was updated. Otherwise it is not possible to reset touch calibration on TFT24 (no touch working)
It is possible to reset touch configuration on TFT24
#1498
> Fix filenames to work on TFT24 to reset settings after firmware was updated

- TFT/src/User/API/Settings.c
- TFT/src/User/API/flashStore.c
The screen orientation is not restored correctly at boot time.
The screen is always restored to the original orientation, however the Touch Screen Calibration (TSC) is restored so you end up with a TFT completely messed up.
> Fix screen rotation not being correctly restored.

- TFT/src/User/Configuration.h
- TFT/src/User/Menu/SendGcode.c
This change adds two commonly used keyboards for central europe layout for the tft7.0 v3 display
QWERTZ (german speaking countries)
AWERTY (french speaking countries) 
Enhanced usability for users of those countries 
No issue is related, just enhancement of useability
> adds keyboard layout for quertz  awerty

- TFT/src/User/Menu/Parametersetting.c
For a printer, 2 hotends add an icon with the temperature of the second hotend to the notification bar.
For a printer with 1 or 3 or more, it remains unchanged
> Notification_icons.

- TFT/src/User/API/Settings.h
- TFT/src/User/Configuration.h
- TFT/src/User/Menu/Selectmode.c
Hey everyone!
I added a compile time option to change the time the boot screen logo is shown.
The parameter is called #define BTT_BOOTSCREEN_TIME and is defined in Configuration.h.
In Selectmode.c i  added a #ifdef BTT_BOOTSCREEN_TIME to check if the parameter is defined, if not the standard time will
be 3 seconds.
Also i changed the CONFIG_SUPPPORT date in Settings.h
This patch adds the possibility to change the time the boot logo is shown at boot as a configuration option in Configuration.h.
This patch is not based on a feature request from someone else, but a feature i needed and wanted to share with the community.
Best regards
pprugger
> Added the possibility to change to time the bootscreen logo is shown

- TFT/src/User/API/Gcode/gcode.h
This PR fixes a bug introduced in PR  #1533 
@Thro42
request_M0() is not exported in gcode.h so the compiler can't find the function in Printing.c
which results in a function call of an empty function.
Best regards 
pprugger
> Fixed implicit function declaration request_M0() in Printing.c

- TFT/src/User/Menu/common.h
line 38 needs to be extern const for this to build in vscode on my machine. could be an error, could be my setup. please test.
> Update common.h line 38 error

- TFT/src/User/Configuration.h
- TFT/src/User/Menu/MeshEditor.c
- TFT/src/User/Menu/MeshTuner.c
- Add `IS_DELTA` to configuration.h
- Prevent `probeHeightStop()` on Delta printers
- Drop Delta printers by 50mm after homing during a Mesh Edit. This amount **should** be enough on most Delta printers to prevent a tower from crashing if the first point used is directly under a tower.
This PR adds a Configuration.h setting for whether or not a printer is a Delta printer. If set to true, then when starting a mesh edit, after homing, the hotend will drop 50mm below the homing point to allow the printer to have free motion to move along X/Y without crashing into the top of the towers. This addresses the issue I brought forward in #1670.
[Video of the hotend …
> Feature delta drop before mesh edit

- TFT/src/User/Configuration.h
DELTA_MBL_Z_DROP_MM *must* be definied as a float instead of an int or double if it's going to be called as a float.
Defining `DELTA_MBL_Z_DROP_MM as an int prevents it from being called since it's being called as a float.
Allows #1677 to function as expected.
> Followup to #1677 Delta drop before mesh edit

- TFT/src/User/API/Printing.c
- TFT/src/User/API/parseACK.c
- Reverts commit #1681 and remove printing menu handling from `ParseACK.c`.  
- Printing menu handling for Onboard SD printing is already handled via `loopCheckPrinting()` in `Printing.c`. 
- In PR #1526 a duplicate printing menu handling was added in `ParseACK.c` which introduces a bug that causes unintentional switching to the Touch mode without proper hardware initializations when a print is started in Marlin mode, resulting in the buzzer being disabled and a non-functional stop button.
> Bugfix: prevent switching to touch mode while printing from Marlin mode, Revert #1681 and remove Printing menu handling from ParseACK.c

- TFT/src/User/API/config.c
- TFT/src/User/API/config.h
- Break MIN_POS_LIMIT into MIN_XY_POS_LIMIT and MIN_Z_POS_LIMIT
- If not a Delta, nothing will change
- If a Delta, set the MIN_XY_POS_LIMIT to -2000 since the center is 0,0
- Fix indent on `case C_INDEX_Z_STEPPERS_ALIGHNMENT`
Delta Printers have their 0,0 coordinates at the center of the bed. `MIN_POS_LIMIT` is hardcoded to `0`, which restricts Deltas to only be able to use 1/4 of the bed for the Pause Position. I propose splitting this into 2 separate values: `MIN_XY_POS_LIMIT` and `MIN_Z_POS_LIMIT`. `MIN_Z_POS_LIMIT` will remain at `0`, whereas `MIN_XY_POS_LIMIT` will be `0` for Cartesian printers, and `-2000` for Deltas.
Allows Deltas to use the entire bed …
> Bugfix delta min pos limit

- TFT/src/User/Menu/SendGcode.c
- Fix: Wrong character width in the Terminal when the first character received has a larger width (originated from #1171). The character info was being fetched only for the first character on a page, this resulted in all the character on the page being rendered with spacing based on the first character's width.
> Bugfix: Wrong character width in Terminal

- TFT/src/User/Menu/PowerFailed.c
`loadLabelText((uint8_t*)okTxt, LABEL_CONFIRM);` function will always to modify MAX_LANG_LABEL_LENGTH of RAM, when the array is only 50, this function will access overflow and tamper with some unknown RAM data.
fix #1720
> fix PLR freeze

- TFT/src/User/API/Gcode/gcode.c
- TFT/src/User/API/Printing.c
- TFT/src/User/API/Settings.c
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/API/parseACK.h
- TFT/src/User/Menu/SettingsMenu.c
- TFT/src/User/Menu/SettingsMenu.h
> RRF Compatibility optimization

- TFT/src/User/API/interfaceCmd.c
> fix M27 not send bug when M27 be cleared in cmd queue. (TFT freeze in "busy process" info menu )

- TFT/src/User/Menu/Print.c
In fact, it is not freeze, the interface is covered by pop-up feedback(echo,error,warning popup windows). The menu index is pop-up, but the interface is gcodes
> fix screen freeze when get onboard SD gcodes

- TFT/src/User/API/Printing.c
- TFT/src/User/API/parseACK.c
* Avoid BOARD_SD be parsed as BOARD_SD_REMOTE in parseACK.c
* Always clear menu buffer when printing menu is active by remote
> fix BOARD_SD_REMOTE flag

- TFT/src/User/API/UI/Numpad.c
- TFT/src/User/Menu/PrintingMenu.c
*  tweak numPadFloat. 
-- Reset key  add sound
-- Also reset the value when click ‘- ‘ and ’.‘ key first time to avoid too many 'del' key required
* restore `oldProgress `to local variable, save 4byte ram
>  tweak numPadFloat &  restore oldProgress to local variable, save 4byte ram

- TFT/src/Libraries/cmsis/stm32f10x/system_stm32f10x.c
- TFT/src/User/API/UI/GUI.c
- TFT/src/User/API/UI/ui_draw.c
- TFT/src/User/Hal/LCD_Init.c
- TFT/src/User/Hal/STM32_USB_HOST_Library/Usr/src/usb_bsp.c
- TFT/src/User/Hal/stm32f10x/lcd.c
- TFT/src/User/Hal/stm32f10x/lcd.h
- TFT/src/User/Hal/stm32f10x/spi_slave.c
- TFT/src/User/Hal/stm32f10x/spi_slave_mks.c
- TFT/src/User/Menu/Selectmode.c
- TFT/src/User/Variants/pin_MKS_TFT32_V1_3.h
- TFT/src/User/Variants/variants.h
- TFT/src/User/main.c
- platformio.ini
This PR adds support for the [ILI9325 LCD](https://cdn-shop.adafruit.com/datasheets/ILI9325.pdf), used by MKS TFT32 1.3 (equivalent to MKS TFT28 V3.0) board. Proposed changes are based on the fork by @Uz45 (https://github.com/Uz45/BIGTREETECH-TouchScreenFirmware)
- Support for ILI9325 LCD
- Support for MKS TFT32 1.3 and MKS TFT28 V3.0 touch controllers (probably older versions too, but can't check those)
- #1792
- #676
- #617
> Add support for MKS TFT32 1.3, TFT28 V3.0

- TFT/src/User/API/UI/Numpad.c
- Fix small font in Numpad when the material theme is diabled. (https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1846#issuecomment-822658704)
> fix small font in numpad

- TFT/src/User/API/Settings.h
- TFT/src/User/API/config.c
- Update config sign after new setting added in #1864 causing invalid settings reading.
- Clean up and reduce memory usage.
Build report:
Device | Old RAM Usage | New RAM usage | RAM Reduced | Old Flash Size | New Flash Size | Flash Size Reduced
-- | -- | -- | -- | -- | -- | --
TFT35 V1.0 | 17544 | 17544 | 0 | 150692 | 148188 | -2504
TFT35 V1.1 | 17544 | 17544 | 0 | 150692 | 148188 | -2504
TFT35 V1.2 | 17544 | 17544 | 0 | 150572 | 148068 | -2504
TFT35 V2 | 18288 | 18288 | 0 | 159984 | 157472 | -2512
TFT35 V3.0 | 18712 | 18712 | 0 | 178244 | 175740 | -2504
TFT35 E3 V3.0 | 18716 | 18716 | 0 | 178924 | 176420 | -2504
TFT35 B1 V3.0 | 18716 | 18716 | 0 | 178924 | 176420 | -2504
TFT43 V3.0 | 18716 | 18716 | 0 | 178936 | 176424 | -2512
TFT50 V3.0 | 18716 | 18716 | 0 | 178936 | 176424 | -2512 …
> Fix corrupt settings after #1864 & reduce memory usage

- Copy to SD Card root directory to update/config.ini
- Copy to SD Card root directory to update/config_rrf.ini
- TFT/src/User/API/parseACK.c
- TFT/src/User/API/parseACK.h
- TFT/src/User/Menu/PrintingMenu.c
- TFT/src/User/config.ini
* improved robustness of Printing menu during a dialog with Marlin (e.g. printing from onboard SD). Now when a dialog with Marlin is ongoing (e.g. M600) pressing on the "Resume" button will be simply ignored and an error message "busy processing, please wait..." is displayed on the notification bar just to inform the user that a dialog with Marlin is ongoing and it must be first completed.
* config.ini has been updated reporting Marlin 2.0.8.1 as the suggested minimum version fully compliant with TFT fw
**PR STATUS:** ready to merge
**NOTE:**
1)  bug https://github.com/MarlinFirmware/Marlin/issues/21813 needs to be fixed in order to cover all the possible Marlin settings
2) PR https://github.com/MarlinFirmware/Marlin/pull/21828 fixing the above bug on Marlin must be …
> improved robustness of Printing menu during a dialog with Marlin

- TFT/src/User/Menu/Babystep.c
- TFT/src/User/Menu/MBL.c
- TFT/src/User/Menu/MeshTuner.c
- TFT/src/User/Menu/ZOffset.c
- TFT/src/User/Menu/common.c
- TFT/src/User/Menu/common.h
If FRIENDLY_Z_OFFSET_LANGUAGE is enabled (in Configuration.h) and inverted Z axis is configured (in config.ini), icons "arrow up"/"arrow down" and labels "up/"down" are used in menus Babystep, MBL, Mesh Tuner and Z offset instead of icons "nozzle down"/"nozzle up" and labels "down"/"up".
fixes #1918
fixes #1926
**PR STATE:** ready to merge
> friendly z offset icons/labels for inverted Z axis

- Copy to SD Card root directory to update/Language Packs/language_de.ini
- TFT/src/User/API/Language/language_de.h
UTF-8 Character "°" to be displayed correctly in german language on TFT70, in order to display unit "°C" of temperatures correctly.
A mistake in the encoding of the previous version of language_de.ini prevents the Character "°" from being fisplayed correctlyl. This regularly happens with "wrong" encoding settings, especially across plattforms.
This change contains correct encoding created on Windows 10 with VIM (Vim Settings :se enc=utf-8 :se fenc=utf-8 :se ff=unix)
Character "°" gets recognized and displayed correctly by utf-8 able IDEs / editors and by the TFT70 display.
This issue may occure also:
- other displays
- other languages
> "°" not displayed correctly in german language on TFT70

- TFT/src/User/API/UI/GUI.c
- TFT/src/User/API/UI/ui_draw.c
- TFT/src/User/API/UI/ui_draw.h
- TFT/src/User/Configuration.h
- TFT/src/User/Menu/PrintingMenu.c
* Alternative live text background color rendering technique on Printing menu made configurable in Configuration.h:
* Uncomment UNIFORM_LIVE_TEXT_BG_COLOR to enable the sampling and use of a uniform background color across all the icons.
* Comment UNIFORM_LIVE_TEXT_BG_COLOR to enable a standard rendering based on the sampling and use, in a pixel by pixel basis, of the underlying icon background colors.
**NOTE:**
* Enable it only in case all the icons have the same and uniform background color under all the live text areas (e.g. applicable to Unified, Round Miracle etc... menu themes).
* If enabled, it speeds up the rendering of the live text and the responsiveness of the TFT, so it can improve the print quality. 
* Suitable in particular for the TFTs with a not fast HW …
> enhancement to live text with uniform bg on Printing menu + bug fix

- TFT/src/User/API/Settings.c
- TFT/src/User/API/Settings.h
- TFT/src/User/API/boot.h
- TFT/src/User/API/config.c
- TFT/src/User/Menu/MeshValid.c
- TFT/src/User/Menu/PreheatMenu.c
- TFT/src/User/Menu/PreheatMenu.h
- TFT/src/User/Menu/PrintingMenu.c
- TFT/src/User/Menu/ScreenSettings.c
- TFT/src/User/SanityCheck.c
- TFT/src/User/Variants/Resolution/TFT_800X480.h
- Remove preheat settings from main settings to reduce RAM usage.
- Misc Clean up.
> Move preheat settings out of settings to reduce RAM usage

- TFT/src/User/Menu/Print.c
- Fix text overlay on icons in file menu with Icon mode. (#2000)
Fixes: #2000
> Fix text overlay on icons in File menu Icon mode

- .github/stale.yml
- TFT/src/User/API/MachineParameters.h
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
- Fix incorrect M914 parsing due to wrong index. (#2036)
- Add `TODO` label to stale bot ignore list.
- 
Fixes #2036
> Fix incorrect M914 parsing

- Copy to SD Card root directory to update/config.ini
- Copy to SD Card root directory to update/config_rrf.ini
- TFT/src/User/API/BabystepControl.c
- TFT/src/User/API/HomeOffsetControl.c
- TFT/src/User/API/ProbeHeightControl.c
- TFT/src/User/API/ProbeOffsetControl.c
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/LEDColor.c
- TFT/src/User/Menu/LevelCorner.c
- TFT/src/User/Menu/TuneExtruder.c
- TFT/src/User/Menu/ZOffset.c
- TFT/src/User/config.ini
- Remove some duplicate code.
- Extruder Calibration/Tuning menu now uses pause/ park location settings instead of hardcoded position.
- Misc code clean-up and reduce some memory usage.
> Remove duplicate code and misc. clean-up

- TFT/src/User/API/HomeOffsetControl.c
- TFT/src/User/API/Printing.c
- TFT/src/User/API/ProbeOffsetControl.c
- TFT/src/User/API/SpeedControl.c
- TFT/src/User/API/extend.c
- TFT/src/User/API/extend.h
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/Hal/stm32f10x/spi_slave.c
- TFT/src/User/Hal/stm32f10x/spi_slave_mks.c
- TFT/src/User/Menu/PrintingMenu.c
- TFT/src/User/main.c
**BUGFIX:**
* fixed #2040. That bug was introduced by PR #2035. The FIL_IsRunout() function needs always to be periodically performed to maintain the proper runout state while PR #2035 avoided to perform FIL_IsRunout() in case of no printing or paused print. In case of runout, resuming the print forced FIL_IsRunout() to return (as initial state) always "false". That value will not allow to resume the print in case the runout sensor uses a not inverted logic (e.g. MKS TFT). In that case that initial value triggers a runout and the print is always forced to pause with no possibility to resume
* improved runout logic. Current runout logic allows to resume the print even in case of a pending runout. In that case the resume will loose/waste (no filament is provided on top of …
> bugfix #2040 + improved #2035 + minor cleanup

- TFT/src/User/API/CaseLightControl.c
- TFT/src/User/API/CaseLightControl.h
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
BTT or MKS TFT
This PR fixes the M355 bug that was introduced by PR #2022, improves case light handling.
Fixes #2052
M355 was not sent again if the first try failed.
Case light adjustment from outside triggered resending the settings again from TFT.
> M355 bugfix

- TFT/src/Libraries/json/JsonListener.hpp
- TFT/src/Libraries/json/JsonStreamingParser.cpp
- TFT/src/Libraries/json/JsonStreamingParser.hpp
- TFT/src/Libraries/json/LICENSE
- TFT/src/Libraries/json/README.md
- TFT/src/User/Menu/RRFMacros.c
- TFT/src/User/Menu/RRFMacrosParser.cpp
- TFT/src/User/Menu/RRFMacrosParser.hpp
- platformio.ini
Improves the macro menu for RRF users
* Adds a streaming JSON parser (C++)
* Streaming parser imported from
https://github.com/squix78/json-streaming-parser
* Parser is MIT licensed, slight modifications to use `char*` and
larger buffer size to match `MAX_PATH_LEN`
* Improves robustness against `,` and `]` in filenames
* Other areas of the firmware that use `M408 S0` can be updated to
use this parser to emit fan speed, speed factor, extrusion factor,
etc.
* Usage of C++ is contained and isolated to parsing only
* Supports the RRF `X_Filename` naming pattern for sort order control
* `X` is a numeric value used to aid sorting [0,any positive integer]
* File and directory names are now sorted
* Filename display omits `X_` for a cleaner look
Additionally enables improvements in all areas …
> Enhance RRF macros menu support

- Copy to SD Card root directory to update/config.ini
- Copy to SD Card root directory to update/config_rrf.ini
- TFT/src/User/API/Settings.c
- TFT/src/User/API/Settings.h
- TFT/src/User/API/SmartFeatures.c
- TFT/src/User/API/config.c
- TFT/src/User/API/config.h
- TFT/src/User/API/config.inc
- TFT/src/User/Configuration.h
- TFT/src/User/config.ini
* Default use `FIL_RUNOUT_PIN` port when multiple extruder and only one filament sensor port. 
* Add the feature of configuring normal open or normal closed of filament sensor port
> fix filament runout sensor bug

- TFT/src/User/API/Printing.c
- TFT/src/User/API/comment.c
- TFT/src/User/API/comment.h
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/Menu/PrintingMenu.c
- TFT/src/User/config.ini
BTT or MKS TFT
This PR adds the remaining time info in the printing screen if the gCode is generated with Cura or IdeaMaker. There's no need anymore to use a plugin to insert M73 commands. In case M73 Rxx is present in the gCode, the comments are ignored, M73 has priority.
Everyone using Cura and/or IdeaMaker.
If there's any other slicer that inserts comments into the gCode file related to total time, elapsed or remaining time please let me know so I can implement that slicer's info too.
> Add remaining time based on comments from gCode file if generated with Cura or IdeaMaker

- TFT/src/User/API/Printing.c
BTT or MKS TFT
There was a bug (introduced by PR #2096) where commands from gCode files were ignored if a comment was present in the same line.
Fixes #2129
> Bugfix - commands ignored if comment is present

- TFT/src/User/API/parseACK.c
- Fix Machine/bed size not parsing correctly from the M115 command's response from the printer.
Fixes #2128
> Fix machine/bed size parsing from M115 response

- TFT/src/Libraries/json/JsonStreamingParser.cpp
- TFT/src/Libraries/json/JsonStreamingParser.hpp
- TFT/src/User/API/Gcode/gcode.c
- TFT/src/User/API/Gcode/gcode.h
- TFT/src/User/API/Gcode/mygcodefs.c
- TFT/src/User/API/RRFM20Parser.cpp
- TFT/src/User/API/RRFM20Parser.hpp
- TFT/src/User/API/RRFParseACK.cpp
- TFT/src/User/API/RRFParseACK.hpp
- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/Print.c
- TFT/src/User/Menu/RRFMacros.c
No new requirements
* Adds `stream_handler` to requestCommandInfo to support >5K payloads
* Adjusts scope of parser/handler in RRFParseACK
* Unlocks icon/grid mode print job listing, fixes #1981
* Resets macro menu cur_page to 0 upon entry (fixes state between print
and macro menus)
* Code in place to support `M20 S3` once the kinks are worked out
Improves RRF support
Addresses #1981 request for print menu icon mode
Verified working on my MKSTFT28
Ready to merge pending reviews.
It seems I've made some memory allocation mistakes when parsing the JSON for `M20 S3` -- it would be greatly appreciated if someone could throw some eyeballs at my changes to see where I goofed? I'm thinking I have some problems around allocating/deallocating `file_name` and `display_name` but can't come to terms …
> RRF: enable A-Z, Z-A, oldest and newest sort in print menu

- TFT/src/User/Menu/LoadUnload.c
RRF users will need to create `/sys/load.g` and `/sys/unload.g` files
Call /sys/load.g and /sys/unload.g macros accordingly in the Load/Unload menu when on RRF
This is generally my load/unload files, parameters for individual machines should be adjusted as appropriate:
`load.g`:
```
; Load filament
M116 P0
M83          ; ensure relative extrusion
G1 E7 F2400  ; fill the short bowden, 45mm
G1 E50 F600  ; continue filling bowden and into the nozzle
G1 E20 F360  ; should see some extrude from nozzle
; ram
G0 E-5 F3600       ;extract filament to cold end area 
G4 S3                 ;wait for three seconds
G0 E5 F3600        ;push back the filament to smash any stringing 
G0 E-5 F3600       ;Extract back fast in the cold zone, helps reduce ooze
; end ram
```
`unload.g`:
```
M116 P0
M83 ; …
```
> RRF: support load/unload menu via load/unload macros

- TFT/src/User/Menu/MachineSettings.c
No new requirements
Removes the Settings -> Machine -> Custom item when on RRF
Removes an unused menu that makes no sense when on RRF
Read to merge
Verified working on MKSTFT28
> RRF: remove unused Settings -> Machine -> Custom

- TFT/src/User/API/RRFStatusControl.c
RRF users **must** remove the `M118` `//action:cancel` `//action:pause` `M409 K"job.file.fileName"` etc. integrations from their config files
These files should be updated to remove the `M409` and `M118` commands that were previously used to notify the TFT of print status changes:
`start.g`
`pause.g`
`resume.g`
`cancel.g`
`stop.g`
Determine print status from M408 requests to determine entry into the print status screen. Automatically updates pause/resume/cancel statuses without `M118` commands.
Reduces configuration burden for RRF users
Ready to merge
Verified to work as expected on my MKSTFT28
#1743 -- this change added print status update support for RRF and called out some config changes required; nothing is altered in this original change, but the config updates are no longer …
> RRF: Remove M118 requirement for print status updates

- TFT/src/User/API/RRFStatusControl.c
No new requirements
Small diff to support an additional state change for detecting a print has finished/canceled: Printing > Busy > Idle
Captures print stop better
> RRF: support printing > busy > idle state transition

- TFT/src/User/Menu/Print.c
No new requirements
Avoid logic trying to load gcode previews in printing menu, some TFTs
crash because of it. Only skipped for RRF
Improves stability of the print menu for RRF users
Ready to merge
Verified working on others' BTT TFT35 V3
> RRF: don't try to show gcode previews

- TFT/src/User/API/UI/ListManager.c
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/menu.c
- TFT/src/User/API/menu.h
- TFT/src/User/Hal/LCD_Encoder.c
- TFT/src/User/Hal/LCD_Encoder.h
- TFT/src/User/Menu/Babystep.c
- TFT/src/User/Menu/Extrude.c
- TFT/src/User/Menu/Fan.c
- TFT/src/User/Menu/Heat.c
- TFT/src/User/Menu/LEDColor.c
- TFT/src/User/Menu/MBL.c
- TFT/src/User/Menu/MeshEditor.c
- TFT/src/User/Menu/MeshTuner.c
- TFT/src/User/Menu/Move.c
- TFT/src/User/Menu/Pid.c
- TFT/src/User/Menu/Print.c
- TFT/src/User/Menu/SelectMode.c
- TFT/src/User/Menu/Speed.c
- TFT/src/User/Menu/TuneExtruder.c
- TFT/src/User/Menu/ZOffset.c
- Remove duplicate code and reduce program memory.
- Remove the need to reset encoder values on every menu.
- The encoder rotation is now converted to Increase/decrease key values using the same `menuKeyGetValue` function, making it easier to use in future.
- Remove unnecessary local variable declaration in **interfaceCmd.c**.
> Clean-up and remove duplicate code 

- Copy to SD Card root directory to update/config_rrf.ini
- TFT/src/User/API/BabystepControl.c
- TFT/src/User/API/BabystepControl.h
- TFT/src/User/API/Gcode/gcode.c
- TFT/src/User/API/Gcode/mygcodefs.c
- TFT/src/User/API/ModeSwitching.c
- TFT/src/User/API/RRFParseACK.cpp
- TFT/src/User/API/RRFParseACK.hpp
- TFT/src/User/API/RRFStatusControl.c
- TFT/src/User/API/RRFStatusControl.h
- TFT/src/User/API/Settings.c
- TFT/src/User/API/Temperature.c
- TFT/src/User/API/parseACK.c
Configure SD card config.g file  M575 P1 S1 
Make the TFT no longer require RRF compatible marlin on the basis of @pfn work. 
Use the M408 S0 to parse most of the information, including temperature, coordinates, and heater status.
synchronize the TFT with the web state.
Separate rrf messages instead of processing them all in parseACK.c,
Reduce unnecessary uart communication,
parseACK.c is not too confusing
> RRF:M575 no longer requires RRF compatible marlin

- TFT/src/User/API/parseACK.c
- Fix Terminal stuck in a loop on receiving a host action prompt or a notification starting with `//action:`. (https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2179#issuecomment-922255059)
The terminal screen was stuck in an infinite loop because the new line `\n` character in **dmaL2Cache** was being replaced in **parseACK.c** by null `\0` character. (Originated from https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/984).
- Remove some duplicate code.
> Fix: Terminal loop/crash on receiving a host action prompt or notification

- Copy to SD Card root directory to update/config.ini
- Copy to SD Card root directory to update/config_rrf.ini
- TFT/src/User/API/comment.c
- TFT/src/User/API/menu.c
- TFT/src/User/Menu/PrintingMenu.c
- TFT/src/User/config.ini
BTT or MKS TFT.
This little PR fixes a GUI glitch with Layer Number display during print. It occurred when the total layer number was unknown and only the printing layer number  was displayed. For the first 10 layers unwanted or extra characters were also displayed. This could also occur if the printing project contained multiple objects and the printing order was object by object and not layer by layer.
"Config.ini" is updated with info for PrusaSlicer users to have layer number info displayed on the TFT during print.
Fixes #2184
> Fix - layer number display glitch

- TFT/src/User/API/UI/Numpad.c
- TFT/src/User/API/coordinate.h
- TFT/src/User/API/menu.c
- TFT/src/User/Menu/Extrude.c
- TFT/src/User/Menu/LoadUnload.c
As I use very often the Load/Unload menu, I found myself many times hitting the temp display zone to set up the nozzle temp but obviously nothing happened... This PR lets you directly select the nozzle desired temperature via numpad right from the menu itself.  Just hit the temperature display zone as you would do in the "Heat" menu.
Another thing done in this PR is the overhaul of the float number input via numpad. Nothing fancy done, just made some changes in the logic behind the input and avoided empty number display field. Maybe easier for users and lighter on MCU and memory.
> Load/Unload menu - direct nozzle temperature select, Numpad float input overhaul

- Copy to SD Card root directory to update/config.ini
- Copy to SD Card root directory to update/config_rrf.ini
- TFT/src/User/API/Language/Language.c
- TFT/src/User/API/Settings.c
- TFT/src/User/Configuration.h
- TFT/src/User/config.ini
There is an issue where names of icons are being expanded by macros before being converted into file names. This affects `LANGUAGE` and `ONBOARD_SD`.
This issue makes anyone working on master require a 0.bmp and 2.bmp because of those settings:
Configuration.h:
```c
/**
* Touch Mode Language
* Select the language to use on the LCD while in Touch Mode.
*
* NOTE: To add/flash a second language copy the required "language_xx.ini" file from
*       "Language Packs" folder to the SD root folder.
*       Then press the reset button to load/flash the copied language file.
*
*   Options: [Primary Language (english): 0, Secondary Language: 1]
*/
#define LANGUAGE  0  // Default: 0
```
icon_list.inc:
```c
X_ICON (LANGUAGE)
```
That is expanding to need `0.bmp` instead of `language.bmp`
The solution …
> Rename these config values so they don't create strange icons.

- Copy to SD Card root directory to update/config.ini
- Copy to SD Card root directory to update/config_rrf.ini
- TFT/src/User/API/Settings.c
- TFT/src/User/API/SpeedControl.c
- TFT/src/User/API/config.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/Speed.c
- TFT/src/User/SanityCheck.h
- TFT/src/User/config.ini
* Allow configurations that will work with Marlin when it has the setting `EXTRUDERS=0`
There are many CNC and laser machines that have no extruders or hotends, but still use Marlin. One place where these machines are very popular is V1Engineering.com (@V1EngineeringInc)
These changes allow ext_count to be zero, as well as hotend_count to be zero. There are a few places where gcode is sent that is specific to extruders (M221 for flow rate, M82 for extruder steps). Those are now gated on having _some_ extruder count.
FYI, If you want to see a configuration that would have EXTRUDERS=0, check out the `V1CNC_SkrPro_Dual_...` from here: 
https://github.com/V1EngineeringInc/MarlinBuilder/releases
The print from Marlin in that configuration is (Notice the `EXTRUDER_COUNT:0`): 
``` …
```
> Extruders zero

- TFT/src/User/API/RRFSendCmd.c
- TFT/src/User/API/RRFSendCmd.h
- TFT/src/User/API/interfaceCmd.c
No new requirements.
Testing help on Marlin and other firmware beside RRF would be appreciated.
When the firmware type is not yet detected, or RRF, send gcode commands with checksums.
Background:
RepRapFirmware 3.4beta4 changed the behavior of checksum handling and now works best when all host gcode is sent with checksums.
Allows using checksum-mode on RRF in 3.4beta4 and later.
Ready to merge pending code review and testing on other firmware.
Verified to work on my MKS TFT28 with RRF 3.3 (I have not yet updated my printers to 3.4 betas)
> RRF: add support for sending gcode checksums

- TFT/src/User/Menu/PrintingMenu.c
If I enable the controller fan, the speed is displayed on the status screen along with the speed of the cooling fan.
This is fine, I can see the speed of all the fans and I can edit them.
But if they start printing, I'm only interested in the speed of the cooling fan and I don't need to see information about the speed of the controller fan on the print screen. This information is confusing.
This PR eliminates cycling between the speed of the chiller and the controller fan on the print screen.
> Controller fan

- TFT/src/User/Configuration.h
- TFT/src/User/Menu/StatusScreen.c
Added the ability to change the color of the values on the live icons on the status screen in the configuration.h file.
Some topics require the inverse display of color values on live status screen icons.
For example: THEME_Rep Rap Firmware Dark
resolves #2272
> Optional value change on the status screen

- TFT/src/User/API/UI/ui_draw.c
- TFT/src/User/Configuration.h
- TFT/src/User/Hal/stm32f10x/Serial.c
- TFT/src/User/Hal/stm32f10x/Serial.h
- TFT/src/User/Hal/stm32f2_f4xx/Serial.c
- TFT/src/User/Hal/stm32f2_f4xx/Serial.h
- Fix Compiling issue when any one of the debug options is enabled in Configuration.h due to undefined variable after #2292.
- Fix preview search by predefined offset not running if `THUMBNAIL_PARSER` is set to 1 (RGB565 Bitmap) or 2 (Base64 PNG) in Configuration.h.
> Fix Compiling issue when any of the debug options is enabled in Configuration.h 

- TFT/src/User/API/menu.c
- TFT/src/User/API/parseACK.c
- Fix a bug where serial data received from the printer was being pushed to debug serial port twice when any of the debug options are enabled in the **configuration.h** file.
> Fix duplicate serial data pushed to debug serial port

- TFT/src/User/API/Printing.c
- TFT/src/User/API/comment.c
- TFT/src/User/API/menu.c
* Fixed a bug with M0, M1 when printing from TFT (SD or USB). In case of M0 or M1 present in the gcode file, upon resume it would dive the nozzle into the bed - and make a nice tattoo there
* Fixed a bug in "printAbort()" function, a loop avoidance was implemented there but it was inactive
* use standard library function 'strlwr' instead of 'lowerCase'
* Reduce the use of magic number
Separated according to the PR of kisslorand https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2291
All the work was done by kisslorand and thank you.
> fix 'printAbort' loopDetected useless bug & 'printPause' M0/M1 have not set 'infoPrinting.pauseType' bug

- TFT/src/User/Menu/TuneExtruder.c
Fixed issue with Tune Extruder menu and Delta printers, before start to extrude a homing is done and then raising Z axis to pause heigh, but this causes a crash at the top of the towers with the motors forcing.
Also improved extrusion speed from 50 to 100 because 50 is really very slow.
> Fix Tune Extruder menu with Delta printers

- TFT/src/User/API/MachineParameters.c
- TFT/src/User/API/SpeedControl.c
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/interfaceCmd.h
BTT or MKS TFT.
This PR eliminates the sending of multiple commands at once. At the moment of sending commands from the queue it is not known if there are more than one slot free in the mainboard's buffer so sending multiple ones at once can lead to missed/not received commands.
A new procedure was implemented that deals with these command groups that need to be sent together. It puts them into the command queue one by one so they will be sent one by one. If there is no room for all of them none is sent. There's a feedback of success if all of them were queued or a feedback of failure if there was an error, in which case none of them is sent. With the existing procedure it was impossible to send all of them or none of them if there was no room in the command queue. 
A lot of approaches …
> Avoid sending multiple commands at once

- .github/workflows/buildBinary.yml
- .github/workflows/buildTest.yml
- TFT/src/User/Variants/pin_GD_TFT35_B1_V3_0.h
- TFT/src/User/Variants/pin_GD_TFT43_V3_0.h
- TFT/src/User/Variants/pin_GD_TFT50_V3_0.h
- TFT/src/User/Variants/variants.h
- platformio.ini
* `GD32F205` for `TFT35 B1 V3.0`, `TFT43 V3.0`, `TFT50, V3.0`
* ` GD35F407` for `TFT70 V3.0`
> add GD32 support for all TFT Series

- README.md
- TFT/src/User/API/Vfs/vfs.c
- TFT/src/User/API/boot.c
- TFT/src/User/API/boot.h
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/Fatfs/myfatfs.c
- TFT/src/User/Menu/ABL.c
- TFT/src/User/Menu/BedLeveling.c
- TFT/src/User/Menu/BedLevelingLayer2.c
- TFT/src/User/Menu/PrintingMenu.c
- TFT/src/User/Menu/UnifiedMove.c
- TFT/src/User/Variants/pin_GD_TFT35_B1_V3_0.h
- TFT/src/User/Variants/pin_GD_TFT43_V3_0.h
- TFT/src/User/Variants/pin_GD_TFT50_V3_0.h
- TFT/src/User/Variants/pin_MKS_TFT28_NEW_GENIUS.h
- TFT/src/User/Variants/pin_MKS_TFT28_V3_0.h
- TFT/src/User/Variants/pin_MKS_TFT28_V4_0.h
- TFT/src/User/Variants/pin_MKS_TFT32_V1_4.h
- TFT/src/User/Variants/pin_MKS_TFT35_V1_0.h
- TFT/src/User/Variants/variants.h
* Some code reduction + cleanup after the last merged PRs
* Used TFT* (e.g. TFT28) folder naming convention also for MKS TFTs: There is no more need to rename to MKS folder. README.md file updated accordingly
**BUGFIXES:**
* Fixed missing check on source filename before trying to rename to .CUR during boot: Small bug originated in #2380.
**NOTE:** Reporting #2295 as fixed just to close it (it was fixed by other merged PRs).
fixes #2403
fixes #2295
**PR STATE:** Ready for merge
> Some code reduction + cleanup

- TFT/src/User/API/UI/ui_draw.c
This is a fix for the embedded base64PNG thumbnail search.
Due to the nature of the thumbnail search order, base64PNG thumbnails were never displayed. While we try to locate an RGB565 thumbnail in the comments, the file pointer moves to the end of the MAX_THUMBNAIL_SEARCH_BLOCKS. The original code tried to locate the base64PNG thumbnail from this position onward, which meant that it was never found.
The fix is to simply seek back to the beginning of the gcode file at the start of the modelFileSeekToThumbnailBase64PNG function.
Base64PNG thumbnails (e.g. PrusaSlicer generated ones) are now displayed correctly.
#2398
> Fixed base64PNG thumbnail search

- TFT/src/User/API/coordinate.c
BTT or MKS TFT with ONBOARD_SD enabled setup 
coordinateQueryTurnOff function does not update the saved coordinate query period. This causes the coordinates not being auto reported by Marlin. As a result during prints from onboard sd, the layer height is not updated on the printing menu.
Layer height is updated on printing menu as intended.
Check description.
> Fix Bug of coordinateQueryTurnOff function

- TFT/src/User/API/Printing.c
- TFT/src/User/my_misc.c
BTT or MKS TFT
If printing from TFT than at print start the progress bar was maxed out and remained like that until a menu refresh was done (after a popup, returning from More menu, Babystep menu, etc).
It is fixed in this PR.
> Fix progress bar maxed out at print start

- TFT/src/User/Menu/BedLeveling.c
With Delta printers there is no need for a second layer/page for ABL because on second layer/page there is only one icon to start ABL.
This PR reduce path to start ABL only for Delta printers, now ABL is starting when clicking on ABL button for ease of use. Before, you had to click on ABL and then on Start on the 2nd layer/page.
> Reduced path to start ABL for Delta printers

- TFT/src/User/API/LCD_Dimming.c
- TFT/src/User/API/LCD_Dimming.h
- TFT/src/User/API/Language/utf8_decode.h
- TFT/src/User/API/Notification.c
- TFT/src/User/API/Printing.c
- TFT/src/User/API/Printing.h
- TFT/src/User/API/RRFParseACK.cpp
- TFT/src/User/API/Temperature.c
- TFT/src/User/Configuration.h
- TFT/src/User/Menu/Popup.h
- TFT/src/User/Menu/PrintingMenu.c
- TFT/src/User/Menu/StatusScreen.c
- TFT/src/User/my_misc.c
- TFT/src/User/my_misc.h
- Add macros for converting time durations to/from milliseconds, instead of using *1000 or /1000 every time. 
- Add function to convert time duration to a formatted time string.
- Remove duplicate code and reduce the size of some const.
- Misc clean up.
> Add time conversion macros and remove duplicate code

- TFT/src/User/API/UI/ui_draw.c
- TFT/src/User/Menu/LevelCorner.c
- TFT/src/User/Menu/MeshValid.c
- TFT/src/User/Menu/PreheatMenu.c
- TFT/src/User/Menu/PreheatMenu.h
- Fix outdated live info code in preheat menu and level cornet menu resulting in freeze after #2448.
- Fix wrong icon draw while pressing heat icon.
Resolves: #2468
> Fix screen freeze and wrong icon draw in heat menu after #2448

- TFT/src/User/Menu/Popup.c
- TFT/src/User/Menu/PrintRestore.c
* Avoid redrawing confused or wrong title, which will freeze the pop-up menu
> Avoid redrawing confused or wrong title, which will freeze the pop-up menu

- TFT/src/User/Menu/TuneExtruder.c
For better accessibility and better access to measurement (with Vernier caliper or a ruler), hotend is now moved at 200 mm height when tune extruder for Delta printers.
> Improve Tune Extruder for Delta printers

- README.md
- TFT/src/User/API/Printing.c
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
* Added Layer Left to **Printing from Host API** reported in README.MD: It can be used by a remote host (e.g. ESP3D, OctoPrint ect...) to display current print layer number and count. It implements #2486.
* Minor cleanup.
**BUGFIXES:**
* Fixed bug with filament runout on mainboard reported in #2483: After a filament change, the nozzle was moved on top of print and it was needed to press on resume button to resume the print.
resolves #2486
fixes #2483
> Added Layer Left in Printing from Host API

- TFT/src/User/API/coordinate.c
- TFT/src/User/API/coordinate.h
- TFT/src/User/Menu/MBL.c
- TFT/src/User/Menu/MeshTuner.c
- TFT/src/User/Menu/ZOffset.c
* Added X and Y coordinates in MBL and Mesh Editor menus: It implements #2385.
resolves #2385
> Added X and Y coordinates in MBL and Mesh Editor menus

- Copy to SD Card root directory to update/config.ini
- Copy to SD Card root directory to update/config_rrf.ini
- TFT/src/User/API/Printing.c
- TFT/src/User/API/Printing.h
- TFT/src/User/API/menu.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/Configuration.h
- TFT/src/User/Menu/PrintingMenu.c
- TFT/src/User/Menu/PrintingMenu.h
- TFT/src/User/config.ini
- TFT/src/User/os_timer.c
**BUG FIXES:**
* Elapsed print time stopped during a print pause/filament runtout etc.: The elapsed print time must not be stopped (e.g. as during the heating phase). It measures the total time to reach the print completion not the active time spent to print. Fix done in function updatePrintTime().
* Progress bar on Printing menu not fully supporting a switch from file based progress to Slicer based progress: As also supported by Marlin, the progress bar is now (as it was before one of the last merged PR) properly supporting the switch from file based to slicer based progress (it means the possibility the progress can be reduced). The fix is done in function reDrawProgress() (a function that is expected to be called only 100 times in a whole print). In general, the Printing menu must make …
> Bug fixes on Printing menu + cleanup

- TFT/src/User/API/MachineParameters.c
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/Move.c
- TFT/src/User/Menu/StatusScreen.c
**BUGFIXES:**
* Fixed #2493
* Fixed #2509
* Fixed out of range array size for XYZ status on Status Screen menu: That bug present since #2448 could cause a freeze on Status screen menu. The array size has been restored to 45 (instead of 10).
* Reviewed XYZ status layout for Portrait Mode in Status Screen and Move menus: Z coord was previously not fully displayed (e.g. on TFT35 V3). Now XYZ are properly displayed (see pictures below).
fixes #2493
fixes #2509
> Fixed #2493, #2509, a possible freeze on Status Screen menu

- TFT/src/User/Menu/Babystep.c
No new requirements, RRF 3.4.0 tested, but should work on any previously working version of RRF.
Removes adjustment and hides display of Z probe offset from babystep screen. It is not useful for RRF
Babystepping on the TFT will no longer mess up the Z probe offset when using RRF
N/A
Verified to work on MKS TFT28 and RRF 3.4.0
> RRF: fix babystepping to not adjust probe Z offset

- .github/workflows/buildBinary.yml
- .github/workflows/buildTest.yml
Various Actions cleanup and fixes in response to [CVE-2022-24765](https://github.blog/2022-04-12-git-security-vulnerability-announced/) that broke the auto-building & committing of updated biniares & config.
*Note: The Build Binaries action will run after the next PR merge/commit since the `.github` folder is excluded.*
Binaries & config will update.
None. Discovered broken actions while checking out recent updates.
> Fix GitHub Actions

- TFT/src/User/API/parseACK.c
This PR parse when Delta Calibration is ended and allow to save settings in EEPROM when enabled or inform process is ended if EEPROM is disabled.
> Save settings after Delta Calibration

- TFT/src/User/Menu/Print.c
On some TFTs there is no SD card detect pin. For those TFTs PR #2351 introduced a bug so SD card cannot be selected as a source for gcode files. This PR fixes it.
Fixes #2539
> Fix  print from SD on TFTs without SD detect pin

- TFT/src/User/API/Temperature.c
- TFT/src/User/API/Temperature.h
- TFT/src/User/API/UI/ListItem.c
- TFT/src/User/API/UI/Numpad.c
- TFT/src/User/API/interfaceCmd.c
BTT or MKS TFT
This PR is a minor code reduction . 
It restores some code reduction that was overwritten by PR #2505 (in "Listitem.c" , "setDynamicValue()") and restores the numpad precision to 5 which was also overwritten by PR #2505 to 4. The listing of parameters allows precision of 5 but the numpad was set back to a limit of 4.
Everyone
This PR is not related to any reported issue.
> Code reduction

- TFT/src/User/API/Settings.h
Merges from 12.VII.2022 brought new icons and new keywords but the "Settings.h" wasn't updated to reflect these changes so a FW update doesn't warn about the need to update language file and icons.
This PR fixes this issue.
> Fix icon and language flash sign

- TFT/src/User/API/coordinate.c
- TFT/src/User/API/interfaceCmd.c
BTT or MKS TFT
In Marlin G90 and G91 gcode sets the extruder also to relative or absolute mode. This change is not reflected in the TFT's FW so in case of these gcode commands the flag for extruder's absolute or relative mode is not updated accordingly which can lead to anomalies. 
E axis coordinate was set wrong if X, Y, Z coordinates were set to relative and E was set to absolute.
This PR fixes these bugs.
~~Possible fix for #2557~~
~~#2557~~
> G90/91 Fix

- TFT/src/User/API/Settings.c
BTT or MKS TFT
After PR #2171 the setupMachine() procedure was prematurely interrupted for RRF resulting in unknown absolute/relative mode of XYZE coordinates, no report of "config.g" settings and the LED not being initialized.
This PR fixes these.
RRF
Fixes #2557
> RRF setupMachine Fix

- TFT/src/User/Menu/Terminal.c
* Improved Terminal menu:
*  Added an history of the last 3 sent gcodes. It allows to load a previous sent gcode from the history instead of re-typing the whole command from scratch.
*  Added a `Clear` button. It allows to clear the current displayed gcode instead of clicking multiple times on `Del` button.
The gcode text box (top left area) in the Terminal keyboard menu provides 3 clickable buttons:
* `Previous` (left button): it scans the history from the last (recent) to the older sent gcodes.
* `Next` (center button): it scans the history from the older to the last (recent) sent gcodes.
* `Clear` (right button): it clears the current displayed gcode (it's not cleared from the history).
A status text is displayed on top of the `Send` button each time one of the 3 …
> Added short gcode history to Terminal menu

- TFT/src/User/Menu/TuneExtruder.c
MKS or BTT TFT
This PR updates current E-steps to be used in the E-steps calibration procedure's formula in  the "TuneExtruder" menu.
It makes sure the right E-steps are used in the E-steps calibration formula.
If E-steps was changed externally (not from the TFT) than the E-steps calibration procedure would not use the real E-steps in its formula resulting in erroneous results.
> Fix TuneExtruder to use current E-steps

- TFT/src/User/API/Printing.c
Restored UPS module function
resolves https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2592
> MODULE BTT UPS and wrong resume printing while Power Off  - #2592

- TFT/src/User/Menu/Terminal.c
BTT or MKS TFT
This PR is a bugfix and an enhancement with the added benefit of firmware flash size reduction.
- fixes a bug where in terminal keyboard if a sent gcode was recalled and sent, it was saved again in a new slot, hence having the same gcode saved in more or all slots available
- gcode sent history recall buttons visible while gcode text area is empty (no input) (credit goes to @rondlh, it is his idea #2609)
People using the terminal menu
As said above, in terminal keyboard if a sent gcode was recalled and sent, it was saved again in a new slot, hence having the same gcode saved in more or all slots available, thus deleting other saved gcodes.
Fixes #2609.
> Terminal rework

- Copy to SD Card root directory to update/config.ini
- Copy to SD Card root directory to update/config_rrf.ini
- TFT/src/User/Configuration.h
- TFT/src/User/config.ini
- TFT/src/User/config_rrf.ini
Disables the autoloading of bed leveling data due to shear number of "Failed to enable bed leveling" reports from users thinking it's a Marlin firmware bug. This question also shows up repeatedly in various Facebook groups.
Probes might be a common upgrade, but they aren't standard on 3D printers yet. Also, leveling types like UBL are not as common as Bilinear, which won't have a mesh to load when the TFT boots up, so this is a more sane default.
Stop false bug reports or confused users blaming Marlin.
> Change "Auto Load Bed Leveling Data" Default to Disabled

- platformio.ini
Fixes deprecation warning with PlatformIO 6.x; i.e.:
```bash
pio run --environment BIGTREE_TFT70_V3_0
Warning! `src_filter` configuration option in section [env:BIGTREE_TFT24_V1_1] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
...
```
#2635
> fix deprecation warning src_filter vs. build_src_filter (#2635)

- TFT/src/User/API/parseACK.c
Currently the FW Retraction menu item is missing from Machine/Settings
Add missing "M" in the parameter
FW Retraction menu appears as expected.
No reported issues that I've seen.
> Fix missing firmware retraction settings menu item

- TFT/src/User/API/LevelingControl.c
- TFT/src/User/API/LevelingControl.h
BTT or MKS TFT
Corner Level menu doesn't take into account if Y axis is inverted or not (introduced by PR #2233). 
This PR fixes it.
- inverted Y axis is taken into account in "Corner Level" menu
- none reported
> Corner leveling bugfix

- TFT/src/User/Menu/ABL.c
BTT or MKS TFT
Exiting from UBL's "Slave to slot" menu, if there was a saving to a slot, there's a popup asking about saving the mesh to EEprom. After making your choice and the popup is gone, your still in the same menu you were about to exit, the "Slave to slot" menu, so you  have to press "Back" again to really exit from that menu.
This PR fixes it, after the popup closes you're out from the "Save to slot" menu.
- as described above, "Save to slot" menu will exit after "Save mesh to EEprom" popup closes
- none reported
> UBL Slave to slot menu Bugfix

- TFT/src/User/Menu/Extrude.c
BTT or MKS TFT
In the "Extrude" menu the displayed extruded amount would reset to 0 (zero) if a popup occurs (ex. current temperature not at desired one, cold extrusion prevention, etc).
This PR fixes it. 
- the displayed extruded amount will not reset upon a popup event
- none reported
> Extrude menu bugfix

- TFT/src/User/API/parseACK.c
BTT or MKS TFT
On multi extruder printers parsing of extruder temperature is broken.
This PR fixes it.
Fixes #2644
Possibly fixes #2637 too.
> Fix temperature parse when multi extruder

- TFT/src/User/API/MachineParameters.c
BTT or MKS TFT
Setting from the TFT's machine settings menu the driver current or TMC hybrid threshold for the extruder(s) is broken. This PR fixes it.
Fixes #2645
> Fix parameter settings

- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
BTT or MKS TFT
Sending `M106 Px` or just `M106` will make the part cooling fan spin at max speed but the status of the fan on the TFT is not updated to 100%.
This PR fixes it.
- show max speed of part cooling fan when "S" parameter is omitted from "M106" command.
- none reported, own finding
- bug is present only if "REPORT_FAN_CHANGE" is not enabled in Marlin
> M106 bugfix

- README.md
Added instructions to README.md for differentiating BTT TFTs and BTT GD TFTs, and which firmware to use for each
Fixes instructions for GD chip BTT TFTs
* #2589 
* #2594
> Add instructions for GD chip BTT TFTs

- TFT/src/User/API/Settings.c
- TFT/src/User/API/Settings.h
- TFT/src/User/Menu/ConnectionSettings.c
- TFT/src/User/Menu/FeatureSettings.c
- TFT/src/User/Menu/LEDColor.c
- TFT/src/User/Menu/Leveling.c
- TFT/src/User/Menu/ScreenSettings.c
- TFT/src/User/Menu/common.c
- TFT/src/User/Menu/common.h
- TFT/src/User/my_misc.c
- TFT/src/User/my_misc.h
- Add CRC16 check to detect changes in settings to remove dependency on unsafe **malloc**.
- Move the Save settings function to Settings.c
> Add CRC16 check to detect change in settings 

- TFT/src/User/Menu/ZOffset.c
BTT or MKS TFT
This PR expands the option introduced by PR https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2633 to allow setting shim thickness in Home/Probe offset menu also.
Just as in "Leveling" menu done by the mentioned PR, it can be set by the "Shim" button selected by sequentially pressing "Next".
> Shim to Home/Probe offset

- buildroot/scripts/auto_copy_firmware.py
- buildroot/scripts/auto_copy_to_sd.py
- buildroot/scripts/auto_gen_language_pack.py
- buildroot/scripts/custom_filename.py
- buildroot/scripts/pre_install_dependencies.py
- buildroot/scripts/short_out_filename.py
- platformio.ini
- Add auto-copy firmware to removable storage/SD card script (Can be enabled by uncommenting `post:buildroot/scripts/auto_copy_to_sd.py` in platformio.ini).
- Make file path generation in scripts safer for cross-platform usage.
- Clean up pre/post-build scripts.
- Remove ambiguous verbose in custom_filename.py
- Disable short_out_filename.py by default.
> Add auto copy firmware to SD card script and cleanup pre/post build scripts

- TFT/src/Libraries/cmsis/stm32f10x/system_stm32f10x.c
BTT or MKS TFT
This PR sets the clock configuration for the STM32F10X connectivity line microprocessors as it should be based on their Xtal/Resonator frequency, rather than the manufacturer of the TFT board.
> MCU Clock config from Xtal/Resonator value

- TFT/src/User/API/Gcode/mygcodefs.c
- TFT/src/User/API/PowerFailed.c
- TFT/src/User/API/Vfs/vfs.c
- TFT/src/User/API/Vfs/vfs.h
- TFT/src/User/Fatfs/myfatfs.c
- TFT/src/User/Menu/StatusScreen.c
* VFS API: all handling logic on `infoFile` data struct (declared in `vfs.h`) is now properly hosted on `VFS` API. Previously, handling such as allocation of infoFile's attributes was provided on both `myfatfs` and `mygcodefs` APIs. The new `addFile` function provided in VFS API is now responsible for the allocation of infoFile's attributes. The changes allow also to hide (remove from vfs.h) some no more needed functions (e.g. `isSupportedFile`). The FLASH space usage is reduced by about 130 bytes.
* Some bug fixes on `scanPrintFilesFatFs` function: e.g. it was used FILE_NUM instead of FOLDER_NUM etc.
* Minor code sharing:  duplicated file sorting code used in `myfatfs .c` is now shared by the use of `sortFile` function
* bugfix on statusScreen_setReady(): possible …
> Improved VFS API

- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/MeshEditor.c
- TFT/src/User/Menu/MeshTuner.c
This PR is an overhaul of the "MeshEdit" menu.
- in case of mesh parsing error a popup would appear, the preparation of that popup's text could have easily cause an overflow with unpredictable outcome, most probably a corrupted memory and/or freeze; it's fixed now
- in calculating the dots shade there are some unsigned variables which could have negative values assigned to them resulting an undefined behaviour; it's fixed now
- the navigation between the mesh points is circular, rows and columns are incremented/decremented in a circular way, they do not stop at their min/max position
- the full GUI is drew only if the full mesh data is loaded
- no more empty mash data menu in case of invalid mesh data
- in case of invalid mesh data now there's a popup announcing it to the user (not a GUI …
> Mesh Editor - Overhaul

- TFT/src/User/API/SerialConnection.c
- TFT/src/User/Configuration.h
- TFT/src/User/Menu/Terminal.c
BTT or MKS TFT
- PR #2678 introduced an unnecessary feature in "Terminal menu", all the forwarded messages to supplementary serial ports are displayed also in the terminal view. It clutters the terminal view, makes harder to follow the things you're interested in, displays all the mainboard's involuntary messages despite having disabled the option to show "temperature" and "wait" ACK in Terminal menu. 
This PR brings back "Terminal" the way it was before PR #2678.
- Messages are added to terminal cache even if you're in the keyboard view so you might end up with already several pages already filled up by the time you get to the terminal view. This PR inhibits the cache filling whilst in the keyboard view. It is made configurable at compile time in "Configuration.h" by enabling or …
> Terminal fixes

- TFT/src/User/API/BabystepControl.c
- TFT/src/User/API/HomeOffsetControl.c
- TFT/src/User/API/Notification.c
- TFT/src/User/API/ProbeOffsetControl.c
- TFT/src/User/API/Vfs/vfs.c
- TFT/src/User/API/Vfs/vfs.h
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/Configuration.h
- TFT/src/User/Fatfs/myfatfs.c
- TFT/src/User/Menu/BedLeveling.c
- TFT/src/User/Menu/MBL.c
- TFT/src/User/Menu/MeshEditor.c
- TFT/src/User/Menu/Popup.c
- TFT/src/User/Menu/PrintingMenu.c
- TFT/src/User/Menu/StatusScreen.c
- TFT/src/User/Menu/Terminal.c
- TFT/src/User/my_misc.c
- TFT/src/User/my_misc.h
**BUG FIXES:**
* Fixed instability bug introduced by #2662: despite the safety code claimed by #2662, the changes applied by that PR (use of strxcpy() function) made the code unsafe. strxcpy is not applicable at all in VFS API where the source buffer's size is always less that the destination buffer's size. strxcpy is not safe in general, meaning an out of buffer read occurs when the source buffer's size is less than the destination buffer's size (as in VFS API). Also strwcpy() and strscpy() were not working (freeze or wrong displayed files navigating on  sd card/usb stick). Proper functions named strncpy_pad()/strncpy_no_pad() are now used
* Fixed instability bug provided by setPrintTitle() function (in Printing menu): the hideExtension()/restoreExtension() functions made visible on VFS …
> Bug fixes on top of last merged PRs

- TFT/src/User/API/LevelingControl.c
- TFT/src/User/API/LevelingControl.h
- TFT/src/User/Menu/LevelCorner.c
- TFT/src/User/Menu/Leveling.c
BTT or MKS TFT
- if home offset in non-zero, the leveling points for the  "Leveling corner" and "Leveling" menus are determined wrong, they are asymmetrical and not respecting the leveling edge parameter (off by the values of the home offset)
- if home offset is non-zero than the minimal edge level value is calculated wrong resulting skipped leveling points measurements
-  just by entering the "L corner" menu the steppers would never auto-disable after the predefined inactivity timeout
- exiting from the "Leveling" menu the nozzle is raised to a predefined value (Config.ini: "level_z_raise") rather than leaving it very close to the bed
- usability of the aforementioned menus for those who have non-zero home offset
- safer nozzle height when exiting from "Leveling" menu
- smaller compiled …
> Leveling points bugfix

- TFT/src/User/API/SerialConnection.c
**BUG FIXES:**
* wrong retrieval of partial message from L1 cache: this scenario typically happens when the TFT receives a burst of messages (e.g. the output for "M420 V1 T1"). The first fully received message (terminated by "\n") is enough to trigger the L1 cache as available (infoHost.rx_ok[portIndex] set to "true") for reading. As consequence, the partial retrieved message is not properly processed by the TFT (e.g. a partial echo message is displayed as an error popup, a truncated message breaks the expected handling etc...).
E.g. the wrong number of rows sometimes displayed on Mesh Edit menu (see attached picture) (e.g. a 6x7 grid instead of the expected 7x7) was caused by this bug.
Probably, the bug occurs more often on not fast TFTs and/or too fast/burst communication speed with …
> Bug fix on partial message retrieval

- TFT/src/User/API/PowerFailed.c
- TFT/src/User/API/Temperature.c
- TFT/src/User/API/Temperature.h
- TFT/src/User/Menu/Extrude.c
- TFT/src/User/Menu/Extrude.h
- TFT/src/User/Menu/LoadUnload.c
- TFT/src/User/Menu/MPC.c
- TFT/src/User/Menu/MeshEditor.c
- TFT/src/User/Menu/Move.c
- TFT/src/User/Menu/TuneExtruder.c
**BUG FIXES:**
* broken "undo/restore" button on Mesh Editor menu: another bug introduced by #2737. In case a mesh value is changed, the undo/restore button doesn't restore the original value on Marlin side
* broken release of memory exiting from Mesh Editor: another bug introduced by #2737. It causes invalid access to mesh data already released (thus possible crashes/freezes/wrong TFT behavior etc...) and that visible delay when closing the menu (e.g. 1-2 seconds on less powerful TFTs)
* wrong move distance selection on Move menu with standard keyboard layout: bug introduced by #2766.
* IDEX Incorrect extrude low temp warning: bug reported and fixed in #2789 by **rondlh** (thank you for your work)
* minor cleanup on files affected by the bugs
**PR STATE:** ready for merge
fixes #2789
> bug fixes on Mesh Editor, Move and on IDEX Incorrect extrude low temp warning (#2789)

- TFT/src/User/API/FanControl.c
- TFT/src/User/API/FanControl.h
- TFT/src/User/API/Printing.c
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
BTT or MKS TFT
This PR fixes the TFT not communicating with the motherboard after it has ben reset (software reset, external reset, watchdog reset, brown out reset)
Fixes #2779
All credit goes to @rondlh, he found the problem and the solution for it, I just expanded it for more possible situations.
~Marked as draft as it is waiting for user feedback~
> MB Reset Fix

- TFT/src/User/API/LevelingControl.c
- TFT/src/User/API/config.c
- TFT/src/User/Menu/common.c
- TFT/src/User/Menu/common.h
- TFT/src/User/my_misc.h
**BUG FIXES:**
* Wrong inverted leveling Y axis: bug introduced by #2655 claimed as bug fix for a not existing bug introduced by PR #2233. The usual propaganda always based on "no bug report from real users" motivated by the life style::
* you did something? I will change it without any reason and even without a perfect knowledge of the code! From now on I will start an infinite rework on that code!
* you re-fixed something I completely messed up for no reason at all (e.g. #2737)? I will even continue to apply my personal changes (not fixing something wrong in your code such as in current #2776, #2778) on top of your real fixes (that I will never even find by myself as all the attempts made in #2786) even if you wasted your free time twice (5 days for original code + 5 for fixes requiring …
> Bug fix on inverted leveling Y axis

- TFT/src/User/API/parseACK.c
BTT or MKS TFT
This is a follow-up of PR #2783, on a MB reset event coordinate awareness has to be initialized to "not known" state also.
> MB reset follow-up

- TFT/src/User/API/AddonHardware.c
- TFT/src/User/API/PowerFailed.c
- TFT/src/User/API/Printing.c
- TFT/src/User/API/RRFParseACK.cpp
- TFT/src/User/API/SpeedControl.c
- TFT/src/User/API/Temperature.c
- TFT/src/User/API/Temperature.h
- TFT/src/User/API/interfaceCmd.c
- TFT/src/User/API/parseACK.c
- TFT/src/User/Menu/Extrude.c
- TFT/src/User/Menu/LoadUnload.c
- TFT/src/User/Menu/MPC.c
- TFT/src/User/Menu/TuneExtruder.c
- TFT/src/User/Menu/common.c
BTT or MKS TFT
This PR makes the tool change requested by the TFT bulletproof. Regardless of any exterior or interior changes occurred to the mainboard the TFT will have the correct tool selected, actions and checks applied to the desired tool.
- The TFT will always work on the desired tool regardless of any prior changes made by the TFT of any external device connected to the mainboard or the TFT.
- FW size reduction
> Tool change rework

- TFT/src/User/API/Printing.c
- TFT/src/User/API/SerialConnection.c
- TFT/src/User/API/SerialConnection.h
- TFT/src/User/Hal/gd32f20x/Serial.c
- TFT/src/User/Hal/gd32f20x/Serial.h
- TFT/src/User/Hal/stm32f10x/Serial.c
- TFT/src/User/Hal/stm32f10x/Serial.h
- TFT/src/User/Hal/stm32f2_f4xx/Serial.c
- TFT/src/User/Hal/stm32f2_f4xx/Serial.h
- TFT/src/User/main.h
**BUGFIXES:**
- Fixed #2761: Based on deep analysis and testing shared by @rondlh on #2761
- Improved partial message retrieval handling: `Serial_Get` finction in `SerialConnection` API improved to prevent the possibility to read multiple times the same partial message on next function invokation
fixes #2761 
**PR STATE:** Ready for merge
> Fixed random pause/hesitation when printing

- TFT/src/User/Menu/ABL.c
With a Ruby nozzle i want it to not touch the bed at X/Y homing position. Once the Z-height is set up correctly (homing + fine-tuning via Baby Steps), the height at Z=0 may be slightly different after UBL + bed leveling enabled.
Better Z-height result at homing position after UBL + bed leveling enabled.
Implements FR #2837
> UBL: implements shift mesh by mesh-mean

- TFT/src/User/API/menu.c
- TFT/src/User/API/menu.h
- TFT/src/User/Menu/Move.c
BTT or MKS TFT
This PR brings small cosmetics to the Move menu.
Y+ and Y- icons were confusing as the icon associated to Y+ clearly shows the bed moving to back and the icon associated to Y- clearly shows a bed mowing forward. As most of printers have the zero position when the bed is fully on the back, moving the bed to the back the Y coordinate decreases and moving the bed to forward the Y coordinate increases.
In this PR the icons representation now correspond to the actual movement of the bed.
The coordinate values on the top of the display got a small attention, they are moved to the same height as reminders and menu names are, when a reminder is displayed, it will remain visible until it naturally goes away, than the coordinate values are visible again.
Before:
After:
> Move menu cosmetics

- .github/workflows/buildBinary.yml
- .github/workflows/buildTest.yml
- README.md
- CI fixes:
- Bump Checkout to V3
- Use Python 3.7
- Update badges in README:
- Link to License
- Use last commit as release date and link to master.zip
- Fix Build Binary CI badge
_Note: The Build Binaries action will run after the next PR merge/commit since the `.github` folder & `*.md` files are excluded._
PR checks & build binary scripts will work again.
None. Noticed that CI tasks were broken again.
> 🔨 CI fixes: Bump Checkout to V3, use Python 3.7 and update README Badges

- TFT/src/User/API/Language/language_am.h
- TFT/src/User/API/Language/language_ca.h
- TFT/src/User/API/Language/language_en.h
- TFT/src/User/API/Language/language_es.h
- TFT/src/User/API/Language/language_gr.h
- TFT/src/User/API/Language/language_jp.h
- TFT/src/User/API/Language/language_nl.h
- TFT/src/User/API/Language/language_pt.h
- TFT/src/User/API/Language/language_sk.h
- TFT/src/User/API/Language/language_sl.h
- TFT/src/User/API/Language/language_tc.h
- TFT/src/User/API/Settings.c
- TFT/src/User/API/Settings.h
- TFT/src/User/Configuration.h
- TFT/src/User/SanityCheck.h
Fix some typos:
- `Z_STEPPER_ALIGNEMENT` => `Z_STEPPERS_ALIGNMENT`
- fillament => filament
- `Z_STEPPERS_ALIGNMENT` define will now also match what is listed in `config.ini`: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/08119fde9b7267c5788725adfb10adb9ef49bcc3/TFT/src/User/config.ini#L693
- Filament will be spelled correctly.
> Fix some typos

- README.md
- TFT/src/User/API/BuzzerControl.c
- TFT/src/User/API/BuzzerControl.h
- TFT/src/User/API/LCD_Colors.h
- TFT/src/User/API/Mainboard_AckHandler.c
- TFT/src/User/API/Mainboard_CmdHandler.c
- TFT/src/User/API/Mainboard_FlowControl.c
- TFT/src/User/Configuration.h
- TFT/src/User/Hal/buzzer.c
- TFT/src/User/Hal/buzzer.h
- TFT/src/User/Menu/ConnectionSettings.c
- TFT/src/User/Menu/Move.c
As discussed with **@rondlh**, just posting here his reviewed PR #2852 to possibly speedup its merge. I used his buzzer implementation based on HW event since a lot of time with no issue at all. All credits to **@rondlh**.
IMHO, with this PR all the more important/useful features have been provided in the TFT and probably it will require from my side just a minor support for maintenance/real bug fixes if any will be reported by users.
This PR also includes a bug fix introduced by last merged PR #2889 causing an infinite sending loop for a gcode purged by the TFT.
Below just the description of this PR as provided by rondlh in his PR #2852.
This pull request consists out of 4 parts, here they are in order of importance:
**1. Print hesitation bugfix.** The current TFT sound …
> Buzzer based on HW Event

- TFT/src/User/API/LCD_Dimming.c
- TFT/src/User/API/LCD_Dimming.h
- TFT/src/User/API/Settings.c
- TFT/src/User/API/Settings.h
- TFT/src/User/API/Temperature.c
- TFT/src/User/API/UI/GUI.c
- TFT/src/User/API/UI/ui_draw.h
- TFT/src/User/API/config.c
- TFT/src/User/Menu/MeshValid.c
- TFT/src/User/Menu/PreheatMenu.c
- TFT/src/User/SanityCheck.h
- TFT/src/User/os_timer.c
- TFT/src/User/os_timer.h
**BUGFIXES:**
- Fixed #2895: Bug introduced by #2889 and affecting TFT variants with a LED on knob (e.g. TFT35 E3 V3.0 etc.) in case `knob_led_idle` setting on `config.ini` file was enabled. The bug caused a freeze exiting from PID/MPC menus or during the `Event LED` process, if enabled, at the beginning of a print. The bug was due to the missing `volatile` qualifier on `ms` attribute of OS_COUNTER data struct.
**NOTE:** The bug severity can be considered major for the affected TFT variants
- Fixed #2898: Bug causing a freeze entering on `Preheat` menu. The bug was present in case the names (e.g. `Poly Carbonate` etc.) defined in `config.ini` file required a pixel width wider that the underlying icon image displayed on the screen.
- Fixed missing default initialization on flash for …
> Bugfixes on top of last merged PR

- TFT/src/User/API/Mainboard_AckHandler.c
Fixes #2912
As of https://github.com/MarlinFirmware/Marlin/commit/3fd175af8ea56db48ea41d7f3d55e967f0df8cd8 / https://github.com/MarlinFirmware/Marlin/pull/26806, Marlin now outputs the `KINEMATICS` type in the `M115` report. This causes `KINEMATICS:<type>` to also be displayed after `MACHINE_TYPE` (printer name) on the main screen in the Status section and on the Info screen.
I tested the old & new `M115` output with this patch and it seems to work correctly.
`KINEMATICS:<type>` will no longer be appended to the `MACHINE_TYPE` (printer name).
- #2912
> Fix MACHINE_TYPE with KINEMATICS in M115

- TFT/src/User/Configuration.h
- TFT/src/User/config.ini
- TFT/src/User/config_rrf.ini
Fixes https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2908
Disable `COMMAND_CHECKSUM` by default to prevent frequent false alarms / error popups. cc: @digant73
- https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2908
> Disable COMMAND_CHECKSUM by default

- TFT/src/User/Configuration.h
- TFT/src/User/config.ini
- TFT/src/User/config_rrf.ini
- White text is a better default than orange. This also matches the current defaults in `Configuration.h`: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/87b6fb332532ffcf2516cb0f7b37465c0d5f8ba2/TFT/src/User/Configuration.h#L407-L411
- Disable title text by default. You should already know that you're in "Marlin Mode" based on the lack of Touch Mode UI.
Better Marlin Mode defaults
> 🚸 Update Marlin Mode defaults
